### ISSUE TITLE
tightvnc Java 2.8.3 won't stay connected to droidVNC-NG 1.3.3

### ISSUE THREAD

**Issue by rnveach** [bk138/droidVNC-NG#101]
**Describe the bug**

TightVnc 2.8.3 for Java fails to stay connected droidVNC-NG 1.3.3.

While the screen is being displayed (top is partially displayed), the viewer gets: "Unsupported encoding code: -1869469441". The number on unsupported changes on every connection.

**To Reproduce**
Install droidVNC-NG 1.3.3 from the playstore.
Setup droidVNC-NG and get all permissions granted.
Download tightvnc Java 2.8.3.
Have tightvnc connect to droidVNC-NG.
Exception occurs.

**Expected Behavior**

Expected to be able to connect to the device with droidVNC-NG 1.3.3 with no exception and be able to control device.

**Logs/Backtraces**

N/A

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.3.3
 - Android version: Pixel 6, Android 13
 - Client-side OS and version: Windows 10
 - VNC client and version: tightvnc Java 2.8.3

**Additional context**

Reverting droidVNC-NG back to 1.2.6 while changing nothing else resolves the issue and connection works and is stable. Don't know the specific version that the break occurs in.

**Comment by bk138** [comment]
This might be due to changes in LibVNCServer. You can help debug the problem by trying with LibVNCServer's [example server](https://github.com/LibVNC/libvncserver/blob/master/examples/example.c) and using [git-bisect](https://git-scm.com/docs/git-bisect) to track down the change that might cause this. The revisions in question are:

* https://github.com/LibVNC/libvncserver/commits/c5c353e9ae0c2a796bc6b0809fd9a5e82b4d27d2 (in droidVNC-NG v1.3.3, bad)
* https://github.com/LibVNC/libvncserver/commits/e3645bcedb229f125eec54a5b3cf2884a4d816be (in droidVNC-NG v1.2.6, good

**Comment by rnveach** [comment]
I am willing to give this a try if no one more experience can at the moment, but I am not very familar with C, cmake, or LibVNC. I am mostly a Java developer but use to do C++ years ago.

I have cloned the repo in ubuntu, I built the project (via https://github.com/LibVNC/libvncserver#how-to-build ), and it is successfully built examples_simple.

I assume I just execute pure `./example` in build and connect to port 5900? I was able to see "Hello World" on RealVNC. I did not get any issues with tightvnc .

**Comment by rnveach** [comment]
There is no rush from me. I would assist by checking other versions of the apk, but there are no other previous releases attached here, and I can't get the source to compile.

**Comment by bk138** [comment]
Thank you, and that being said, there _are_ more .apk's available at https://f-droid.org/packages/net.christianbeier.droidvnc_ng/ - though not all, they seem to make available only the last three...

**Comment by rnveach** [comment]
Installed the oldest, 1.3.1, and the issue persists there.

Stack trace for info:
````
java.lang.IllegalArgumentException: Unsupported encoding code: -1864939777
        at com.glavsoft.rfb.encoding.EncodingType.byId(EncodingType.java:142)
        at com.glavsoft.rfb.encoding.decoder.FramebufferUpdateRectangle.fill(FramebufferUpdateRectangle.java:61)
        at com.glavsoft.rfb.protocol.ReceiverTask.framebufferUpdateMessage(ReceiverTask.java:151)
        at com.glavsoft.rfb.protocol.ReceiverTask.run(ReceiverTask.java:85)
        at java.lang.Thread.run(Thread.java:748)
````

**Comment by DeadSamurai8** [comment]
> **Describe the bug**
> 
> TightVnc 2.8.3 for Java fails to stay connected droidVNC-NG 1.3.3.
> 
> While the screen is being displayed (top is partially displayed), the viewer gets: "Unsupported encoding code: -1869469441". The number on unsupported changes on every connection.
> 
> **To Reproduce**
> Install droidVNC-NG 1.3.3 from the playstore.
> Setup droidVNC-NG and get all permissions granted.
> Download tightvnc Java 2.8.3.
> Have tightvnc connect to droidVNC-NG.
> Exception occurs.
> 
> **Expected Behavior**
> 
> Expected to be able to connect to the device with droidVNC-NG 1.3.3 with no exception and be able to control device.
> 
> **Logs/Backtraces**
> 
> N/A
> 
> **Your environment (please complete the following information):**
>  - droidVNC-NG version: 1.3.3
>  - Android version: Pixel 6, Android 13
>  - Client-side OS and version: Windows 10
>  - VNC client and version: tightvnc Java 2.8.3
> 
> **Additional context**
> 
> Reverting droidVNC-NG back to 1.2.6 while changing nothing else resolves the issue and connection works and is stable. Don't know the specific version that the break occurs in.
>

**Comment by bk138** [comment]
Alright, tried the following which is as close as possible to your setup @rnveach but it works :shrug: 
* downloaded https://www.tightvnc.com/download/2.8.3/tvnjviewer-2.8.3-bin-gnugpl.zip
* started with `java -jar tightvnc-jviewer.jar` using 
```
java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)
```
* Connecting to droidVNC-NG v1.3.3 without password
* works...

Maybe it's the Windows Java?

**Comment by bk138** [comment]
Tentatively closing, feel free to post something if there's new info.

**Comment by rnveach** [comment]
Sorry for the delay as I was at my job around the clock last week.

> Edit: Just tried with v1.3.3 and am able to reproduce your issue. So it seems v.1.3.4 has this fixed. Are you able to confirm?

I just installed 1.3.5 and yes, it is working now and isn't disconnecting me instantly. I am sorry I did not mentioned I set a password, but I figured that was something trivial.
