### ISSUE TITLE
mouse cursor too small while scaling

### ISSUE THREAD

**Issue by Flash-ang** [bk138/droidVNC-NG#103]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Is your feature request related to a problem? Please describe.**
when view on scaling, the mouse cursor is too small.

**Describe the solution you'd like**
may be fix a cursor size, or option for S / M / L / XL size cursor.

**Comment by bk138** [comment]
As the mouse cursor is simply just part of the scaled screen, and not drawn by droidVNC-NG, I see no easy way of making it bigger. You probably have to change your Android settings. for that.
