### ISSUE TITLE
Feature: Server-to-client copy/paste would be nice

### ISSUE THREAD

**Issue by KJ7LNW** [bk138/droidVNC-NG#106]
**Is your feature request related to a problem? Please describe.**

I am unable to copy from Android and paste locally to my desktop.

**Describe the solution you'd like**

Support copy-paste of plain-text content

**Describe alternatives you've considered**

Even if I have to paste the text into a "clipboard transfer" box on the droidVNC-NG app itself, that would be ok, but even better if you can transfer the clipboard as soon as text is copied!

**Additional context**

If this is actually known to work, then let me know I should troubleshoot.

Thanks!

**Comment by bk138** [comment]
Please see the third bullet point in https://github.com/bk138/droidVNC-NG#features: Android keeps services/apps from getting clipboard data. We could have the  "clipboard transfer" box you suggested, that would work but probably be not very good UX :-/

I'm keeping this open as it might relate to #4

**Comment by KJ7LNW** [comment]
Interesting point.

I'd like to highlight this from the original post above:

> Even if I have to paste the text into a "clipboard transfer" box on the droidVNC-NG app itself, that would be ok, but even better if you can transfer the clipboard as soon as text is copied!

This was my case:

I used my phone to scan a QR code with TOTP keys, but wanted to _securely_ transfer the (very long) key to my desk without re-typing it.  So I setup ssh forwarding and tried droidVNC-NG hoping clipboard would work.

For this example I would be fine pasting it into a dedicated "clipboard" textarea of the droidVNC-NG app itself so it lights up the clipboard on my desktop client so I can paste to my desk.

**Comment by freebrowser1** [comment]
Weird, for me this did work.
Using RealVNC viewer on macOS copying text from Android (OnePlus 6 running Android 10) to my Mac did work.

**Comment by ElishaAz** [comment]
KDEConnect solved the Android 10 problem by opening an invisible activity that retrieves the clipboard: https://github.com/KDE/kdeconnect-android/blob/master/src/org/kde/kdeconnect/Plugins/ClibpoardPlugin/ClipboardFloatingActivity.java
This can only be done on-demand, but is still much better than having to paste it into a text field

**Comment by bk138** [comment]
Note to self: https://developer.android.com/reference/android/view/accessibility/AccessibilityEvent#TYPE_VIEW_TEXT_SELECTION_CHANGED
