### ISSUE TITLE
UI Issue - unwanted floating notification

### ISSUE THREAD

**Issue by zawsx** [bk138/droidVNC-NG#107]
Hi! Thanks for doing this, works really well and for me is a step forward :)
I use a Xiaomi phone running their MIUI 13 which I suppress as much as possible as all I want is the underlying Android 12
I cannot get rid of the intrusive 'floating' button despite rebooting the phone - the NG app is not set to start on boot.
![Screenshot_2022-10-09-09-58-57-152_com mi android globallauncher](https://user-images.githubusercontent.com/6049993/194750108-a808b9c3-2bc6-4cdd-ba40-b9c59476a456.jpg)
Pretty sure it's not a config issue with the phone itself as the app is stopped, I've removed all the permissions I can find and rebooted. None of the hundreds of other installed apps suffer from this unwanted exhibitionism.
Glad of any pointers - it's obviously trivial because I can install on demand so not a bug, just a wish-list item for me and maybe others :)

**Comment by bk138** [comment]
Well there is the service's notification that shows that there's something in the background. You have it at a really unusal location, this is not something that the app does.

**Comment by zawsx** [comment]
Thanks! Really appreciate the time you took to respond :)
No other apps, many of which run in the background when in use, do it. 
Looks as if something about this app triggered the floating icon.
It may be an OEM thing but I don't think it can be because it is running in the background as I've restarted. Unless there's a fault in the app where it runs even though 'start at boot' is off. 
Guess there's no 'do not display app as a floating icon' flag you can set...

**Comment by bk138** [comment]
Well, there is no "floating icon" functionality in the code at all :-). I've never seen this - what happens if you click it?

**Comment by zawsx** [comment]
Nothing. It can be repositioned but only on the edges of the screen and not on the top or bottom areas. There is no 'execute' method I can find - nothing happens when you single-tap, double-tap etc. A byproduct of Android or MIUI I guess but it doesn't help as I can't remove it and no other apps suffer. I suppose it could be a recent update and this is the first instance. As you wrote, absolutely nothing to do with the droidVNC-NG code. If ever I discover why I'll let you know in case it helps. Thanks again for taking the trouble to look into it.

**Comment by cannondale0815** [comment]
@zawsx The floating notification is a result of choosing the "shortcut" option in the Accessibility settings for an app in Android. Go to the Accessibility settings of Android, then click on the app, then slide the second slider ("shortcut") into the off position.

**Comment by StevanWhite** [comment]
Hi, Christian!

I would suggest putting this information in an FAQ, or in the README or some other top-level document,
along with terms that might help finding it "floating" "button" "icon" "U" ...

It was bothering me, and it took a good 15 minutes to discover the issue here!

Cheers!
