### ISSUE TITLE
Fire OS restarting ok TV standby

### ISSUE THREAD

**Issue by hadihashem** [bk138/droidVNC-NG#110]
Hello 
I installed DroidVNC on my Fire TV stick connected on a TV device
When starting capturing the server works as expected
But when I turn off the TV (Standby Button) then turn on again (shortly or after a few seconds) the Fire TV stick restarts (something like power reset)
If I turn off the TV when capture mode is stopped, nothing happens and I can turn it on again without having my Fire TV stick restarted, which is the normal behavior before I install DroidVNV
I have a similar setup on another Fire TV stick device connected to another TV of a different brand
I do not experience the same problem
Can you please give me some ideas where to start digging to identify the issue?
Thanks in advance and regards

**Comment by bk138** [comment]
Very hard to tell what exactly is happening without debug logs. Some ideas:

* Try with another TV. You already did that. This hints at the TV being the culprit.
* Try with another droidVNC-NG setup (no screen capturing, no input, ...) and note what happens.
* If it's screen capturing, try with ScreenRecorder as noted [here](https://github.com/bk138/droidVNC-NG#notes).
* Finally, get some debug logs. No idea how this is done with a Fire Stick but a search engine might help.

HTH!

**Comment by hadihashem** [comment]
Hello
I switched to another HDMI port of the same TV and the error is gone
I guess something was wrong with the former HDMI port I was using 
Thanks for the hints
Regards

**Comment by bk138** [comment]
Alright, nice to read that your issue is solved.
