### ISSUE TITLE
Black screen / Screen Capture Denied on boot

### ISSUE THREAD

**Issue by Nephilimi** [bk138/droidVNC-NG#114]
When using the "Start on Boot" feature the VNC server does start but shows Permission Screen Capturing Denied and sometimes Unknown. At this point remote VNC connections will connect but will show a black screen. Inside droidVNC-NG hitting the stop button and then the start button again gets the Screen Capture permission Granted, no other dialog shown. Little strange behavior but it does work after toggling the service.

Discovered workaround; Using app [Auto Start](https://play.google.com/store/apps/details?id=com.autostart&hl=en_US&gl=US). Set a 10 second delay and then have it trigger droidVNC-NG. 

My theory is there isn't something started in the system when droidVNC-NG starts and it needs more time before it will work. Maybe we need a start delay in droidVNC-NG? 

This is a rather "special" android HMI, this is what it shows in system settings
Model; rk3288 
Vendor; ysta6212
Build; rk3288-userdebug 9 pi 202110605.104254 release-keys
Android 9

**Comment by Nephilimi** [comment]
I think I have root on these (I'll check), can you tell me what I should add where in that file?

**Comment by bk138** [comment]
> I think I have root on these (I'll check), can you tell me what I should add where in that file?

You can add a `Thread.sleep(10000);` https://github.com/bk138/droidVNC-NG/blob/master/app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java#L261 but it might cause an [ANR](https://developer.android.com/topic/performance/vitals/anr). if it does, we have to think about some other approach.

**Comment by shungabubus** [comment]
good one, but it also appear on 7.1.1 at fresh installed manual start. Thank you for the hint, the STOP restart worked!

**Comment by bk138** [comment]
Looked into this a bit more, it seems it might be due to the main service launching several shortlived transparent activities in order to display dialogs asking for permissions.
