### ISSUE TITLE
Red and Blue colours swapped with UltraVNC 1.3.8.1 on Windows 11

### ISSUE THREAD

**Issue by arminlinder** [bk138/droidVNC-NG#115]
Strange effect:

if I have the connection settings on "Auto select best", or set to "Full color", the colors are messed up, blue, for instance, gets kind of orange/brown. Only green appears green. If I set the colors to "256 colors" the colors look allright, but picture quality is, of course, rather poor.

See here to see yourself:

[False colors tablet](https://www.arminlinder.de/temp/false_colors_tablet.jpg)
[False colors mobile](https://www.arminlinder.de/temp/false_colors_mobile.jpg)

Colors are allright if I view a Windows host from a Windows client.

Probably an issue with UltraVNC? Or with the quite outdated Android version? Anyone with a different VNC got this issue too? Any clues whether I can change a setting anywhere to fix this?

Thnx, Armin

Host (tablet) is DroidVNC-NG 1.3.5 on Android 8.1.0, Samsung Galaxy Tab SM-T580
Host (mobile) is DroidVNC-NG 1.3.5 on Android 8-0-0, Sony Xperia XZ
Client is UltraVNC 1.3.8.1 on Windows 11

**Comment by bk138** [comment]
Looks like the red and blue channel got swapped. Your best bet is to try with a different viewer and/or play around with the color depth (32bit works best, indexed colours are known to be problematic...)

**Comment by arminlinder** [comment]
Thank you very much for the quick response. Right! Tried with TightVNC, and the effect is gone.

Seems to be a problem with UltraVNC.
