### ISSUE TITLE
DroidVNC + Android tv 11

### ISSUE THREAD

**Issue by B15cut3r** [bk138/droidVNC-NG#116]
Hello.
I am trying to find a vnc server to install on my Philips Smart tv with Android tv 11 in order to be able to connect to it from my pc remotely and not in person and to be able to access the configuration of its applications. It is important that the session can be carried out in the background, that is, without interfering with a possible active live TV display.
I read good recommendations about your app and tried it by installing it on an Android phone and I was able to connect from both the Tightvnc viewer and the Realvnc viewer, although I couldn't get the session to take place in the background.
The problem is that when I access Google Play from my Smart TV, it does not offer me the installation of its application. I would like to know if your app is compatible with my Philips 55PUS7406/12 and I can install it without problem from an apk or if my device is not compatible with your app; as well as some guidance on how to run sessions in the background.
Thank you.

**Comment by bk138** [comment]
I honestly don't know if the app is compatible with a "Philips 55PUS7406/12". You should try it out yourself. If you can't get the app from the Play Store, you might be able to use F-Droid or sideload it via USB cable and adb or SD-card and file manager. For running in the background without permission asking (on Android 10 and newer), see https://github.com/bk138/droidVNC-NG/blob/master/README.md#notes 

HTH!
