### ISSUE TITLE
tightvnc client only connects to droidVNC-NG once in 100 times

### ISSUE THREAD

**Issue by sillyquestion** [bk138/droidVNC-NG#117]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

tightvnc client only connects to droidVNC-NG once in 100 times

**To Reproduce**

**Expected Behavior**

**Logs/Backtraces**

Log on mobile side - don't know how to access. On client side:
Started and Winsock (v 2) initialised
Buffer size expanded to 4352
Registered connection with app
Connected to 192.168.1.2 port 5900
  reading 12 bytes
RFB server supports protocol version 3.8
  writing 12 bytes
Connected to RFB server, using protocol version 3.8
  reading 1 bytes
  reading 2 bytes
  writing 1 bytes
Enabling TightVNC protocol extensions
  reading 4 bytes
  reading 4 bytes
  reading 16 bytes
  writing 4 bytes
Authentication scheme: Standard VNC password authentication
  reading 16 bytes
  writing 16 bytes
  reading 4 bytes
Deregistered connection from app
Exiting
VNC viewer closing down

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.3.5
 - Android version: 10
 - Client-side OS and version: Windows 11
 - VNC client and version:TightVNC 1.3.10

**Additional context**

**Comment by bk138** [comment]
Works for me with TightVNC 1.3.10. Did you try with another client or another Android device?

**Comment by spi43984** [comment]
I am using the remmina built-in vnc client and couldn't connect as long my colour settings were set to worse than 16bpp.

**Comment by gitgrub** [comment]
Works good here with tightvnc 2.8.63 from win10 to android 11.

**Comment by bk138** [comment]
Tentatively closing this since there is no new info from op. Feel free to post here once new info is available.
