### ISSUE TITLE
UI for reverse connection without listening connection

### ISSUE THREAD

**Issue by rdiez** [bk138/droidVNC-NG#118]
First of all, many thanks for this app.

I use VNC on Linux and Windows very often, and I only use reverse connections. Reasons are:

1) Better security. I only start the receiving viewer on demand, so it is not always reachable, and the VNC server never needs to listen on any TCP port, so it is never reachable.

2) Most people cannot reconfigure their Internet routers to open a port anyway.

The trouble is, droidVNC-NG insists on starting the listening server, and option "Start on Boot" defaults to on, which worries me. When you log on to some WLAN in some hotel or airport, you never know if someone will then scan your TCP ports.

Because I never want to start droidVNC-NG automatically, I think that the "Start on Boot" option should be off by default.

But more importantly, I would like the ability to make a reverse VNC connection without having to enable the listening VNC server first.

I know I can set up a complicated password, but a) the user may forget to do that, and b) that would not help against any vulnerabilities the VNC server may have in the connection handling or password verification code.

**Comment by bk138** [comment]
You can set the port to -1 to not have a listing server as per 72014eb5a46cae9a635239db4429e1276f84823e. This should be presented better in the UI, so I'm leaving this open for the UI improvement.

**Comment by rdiez** [comment]
OK, thanks for the info!

**Comment by rdiez** [comment]
I just tried, and I cannot enter "-1" in the field. I cannot even paste it as a string I copied from somewhere else. I am guessing that the field validation is set to unsigned integers only.

The commit you referenced is many months old and should be included in the current F-Droid version 1.3.5, is that right?

**Comment by bk138** [comment]
> I just tried, and I cannot enter "-1" in the field. I cannot even paste it as a string I copied from somewhere else. I am guessing that the field validation is set to unsigned integers only.

Might well be. I guess you have to wait for #98 then, sorry :-/

 
> The commit you referenced is many months old and should be included in the current F-Droid version 1.3.5, is that right?

Yes!
