### ISSUE TITLE
Possible to add support for videos?

### ISSUE THREAD

**Issue by sdaau** [bk138/droidVNC-NG#12]
Fantastic software, thanks a lot for it!

It installs fine on a projector device of mine with Android 9, works fine - except, when I play videos (e.g. via NewPipe), then I get a black screen.

I don't really care all that much about quality, it might just as well send 1 frame per second over VNC, as long as there is a picture of the video shown, instead of just a black screen, in the VNC viewer.

Thanks again!

EDIT: Just noticed that this has to do with, whether the videos are rendering on the GPU or not. So the answer to this question is most likely "no"... I've tested this, by trying Kodi, setting it (cannot remember how exactly now) to "software rendering" somewhere - and those kind of videos do appear through droidVNC-NG on a VNC client/connection... So this is not droidVNC-NG's problem per se.

**Comment by bk138** [comment]
Videos should be supported just fine. Do apps like https://f-droid.org/de/packages/com.orpheusdroid.screenrecorder/ record something for you? It uses the same API.

**Comment by bk138** [comment]
Tentatively closing, feel free to come back once there is more info.
