### ISSUE TITLE
Can connect but cannot input after long standby

### ISSUE THREAD

**Issue by va663** [bk138/droidVNC-NG#120]
ENV: 
vnc-ng 1.3.5
Android 8.1.0

DESC:
After about 3~5 days, I can connect but cannot perform any operations, and it returns to normal after stop and start.
Sorry, can't provide more information as I don't know much about it.

**Comment by bk138** [comment]
Thanks for the report @va663 - this sounds very much like #113, isn't it? I'll flag this as a duplicate, correct me if I'm wrong please.

**Comment by va663** [comment]
> Thanks for the report @va663 - this sounds very much like #113, isn't it? I'll flag this as a duplicate, correct me if I'm wrong please.

Yes, it seems to be a similar problem, but the situation I encountered is that the device can be connected and the home key can also be sent, but the touch screen (or mouse operation) does not respond.
Perhaps the two issues are related。

**Comment by va663** [comment]
> Thanks for the report @va663 - this sounds very much like #113, isn't it? I'll flag this as a duplicate, correct me if I'm wrong please.

After reading the discussion of https://github.com/bk138/droidVNC-NG/issues/113, I found that I can't help at all, the technology involved is too profound ><.
But I'm more sure that the two issues are related.

Thanks
