### ISSUE TITLE
Halp? Streaming to v4l2loopback device

### ISSUE THREAD

**Issue by Rstment25** [bk138/droidVNC-NG#128]
What I'm trying to do is stream from the phone > capture that stream on PC and pass it into v4l2loopback device : creating a virtual webcam, which would display phone screen ( Any app which has access to webcam would be shown phone display )

I'm having a bit of an issue figuring out how to do this tho...

I found this command online:
ffmpeg -re -listen 1 -i rtmp://localhost:5050/ \
  -c:v rawvideo -an -pix_fmt yuyv422 \
  -f v4l2 /dev/video1

(It uses ffmpeg to grab video from rtmp://localhost:55555 and then passes the video via v4l2loopback to virtual device /dev/videoX )

The issue is they are grabbing rtsp/rtmp streams, and this app streams via vnc ... so I am not sure how to direct ffmpeg to grab video from vnc server? If at all possible... 

Changing the code to this:

ffmpeg -re -listen 1 -i vnc://phone.ip.adress:5050/ \
  -c:v rawvideo -an -pix_fmt yuyv422 \
  -f v4l2 /dev/video1

Spits out this error:

vnc://phone.ip.adress:5900: Protocol not found

So I guess ffmpeg doesn't know how to open vnc stream...

Any ideas what to use instead?

I pulled the code from this discussion on how to pass obs stream into a virtual webcam:(https://obsproject.com/forum/threads/obs-to-v4l2loopback.62677/)

**Comment by bk138** [comment]
Hi! Please don't use the issue tracker for questions, there is a community chat over at https://app.gitter.im/#/room/#droidVNC-NG_community:gitter.im with probably more audience.

For your ffmpeg issue, the folks over at ffmpeg are probably more knowledgeable.

You might also want to try (for different approaches):
* https://github.com/LibVNC/libvncserver/blob/master/examples/client/vnc2mpg.c and then just display the mpeg stream with VLC or gstreamer or whatever or
* https://gstreamer.freedesktop.org/documentation/rfbsrc/index.html#rfbsrc-page directly, which seems cleaner. Again, the gstreamer folks and website know more.

**Comment by Rstment25** [comment]
> Hi! Please don't use the issue tracker for questions, there is a community chat over at https://app.gitter.im/#/room/#droidVNC-NG_community:gitter.im with probably more audience.
> 
> For your ffmpeg issue, the folks over at ffmpeg are probably more knowledgeable.
> 
> You might also want to try (for different approaches):
> 
> * https://github.com/LibVNC/libvncserver/blob/master/examples/client/vnc2mpg.c and then just display the mpeg stream with VLC or gstreamer or whatever or
> * https://gstreamer.freedesktop.org/documentation/rfbsrc/index.html#rfbsrc-page directly, which seems cleaner. Again, the gstreamer folks and website know more.

Sorry I forgot to check if there's any group...

And thanks for the links ! I don't know how to use them right now but I'll try to figure it out
