### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by pr4x77** [bk138/droidVNC-NG#129]
Hi,

sometimes when I try to connect I get an error using bVNC. I will attach a screenshot. Other VNC clients arent working anymore too then but wont give such an detailed error.

I cant reproduces this error consistently. It just happens sometimes over the day. 

 - droidVNC-NG version: newest Playstore Version
 - Android version: 12
 - Client-side OS and version: android 12
 - VNC client and version: bVNC but with other clients doesnt work either

Some one can help?

Here is the error:
![Screenshot_20230314-135700](https://user-images.githubusercontent.com/126170201/225009327-bed82292-ef74-46ca-8e12-4c7c8a77daca.png)
![Screenshot_20230314-135711](https://user-images.githubusercontent.com/126170201/225009351-29855a72-224b-4f81-983a-56c0822bd288.png)

Thanks!

**Comment by pr4x77** [comment]
Couldnt reproduce it by now but it seems that DroidVNC crashed and wasn't running anymore. I will try to reproduce it.

I go another error today. I was able to connect the whole day but after long time running I wasn't able to control anything anymore. I just could only watch the display nothing more. I made a logcat but don't know what I have to look for.

I checked the granted rights and DroidVNC was still running with all rights granted but could control anything. Different VNC Viewers tested.

**Comment by bk138** [comment]
Your other issue sounds like #121 and/or #113.

**Comment by pr4x77** [comment]
I don't have any OutOfMemoryException as mentioned in #113 

Is there a fix or a way to test for #121 ? I already tried different vnc viewers like bVNC, Multi VNC, Ultra VNC, Tightvnc. None of them is able to control the device. 

Just to give more details, the screen isn't freezed. I can watch the display change using the vnc connection if I control it locally after the problem occurs. Im just not able to take any action.

**Comment by bk138** [comment]
Just saw that I owed you an answer. No, different resolutions should not pose a problem. The only thing I can think of is to gather more info by means of debug logs...

**Comment by bk138** [comment]
@pr4x77 can you check if the problem persists with the newest version?

**Comment by bk138** [comment]
Tentatively closing, please post here in case there is new info.
