### ISSUE TITLE
Zebra MX Famework - Automatic grant permission

### ISSUE THREAD

**Issue by pieewiee** [bk138/droidVNC-NG#130]
I am really impressed by the work you did here and i want to participate here by creating a custom version for my zebra devices. 

**Problem**
Zebra provides a very powerful MX framework to do certain things on the devices (Filetransfer, Grant privileges). Isomehow need to grant the privileges for input and screen casting automatically for the zebra devices. 

**Things tried**
i tried to utilize the [Access Manager ](https://techdocs.zebra.com/stagenow/5-8/csp/access/)but i didn't found a way to assign those privileges.

**Describe alternatives you've considered**
Is there maybe a file on the filesystem that i can manipulate? the MX framkwork can access different partitions which a normal user does not have access to. 

**Your environment (please complete the following information):**
 - droidVNC-NG version: latest
 - Android version: 11

**Comment by bk138** [comment]
Hi! Please use https://gitter.im/droidVNC-NG/community to ask general questions 🙂.

Regarding your question: droidvnc-ng actually uses 3 different kinds of permissions:
* for file access, it's a common 'dangerous' permission (in android parlance)
* for input, it uses an a11y service that needs to be activated by the user. Don't know if there's any automatic way.
* for screen capture, the permission can probably made permanent through appops.

HTH!
