### ISSUE TITLE
 Request for Screen and Click Event Access without File or Screen Recording Permissions

### ISSUE THREAD

**Issue by diankourenxia** [bk138/droidVNC-NG#133]
Hello,

I am interested in using droidVNC-NG to capture screen streams and click events, but I do not require file or screen recording permissions. I would like to avoid the authorization prompt that requests these permissions.

Is it possible to configure droidVNC-NG to only request access to the screen and click events, without requesting file or screen recording permissions? If so, could you please provide some guidance on how to do so?

Thank you for your help!

**Comment by bk138** [comment]
You can do in principle without file permission, this is being worked on in #95. 

You cannot, however, capture the screen without the proper permission (unless you've signed the app with the platform cert, that is). You can see the README for how to permanently give the screen record permission.
