### ISSUE TITLE
Show mouse pointer

### ISSUE THREAD

**Issue by simpleuserdontwatch** [bk138/droidVNC-NG#137]
Hello, I would like to suggest an idea for project.
Adding mouse pointer to show mouse position of vnc client. 
Example on a image because I am bad at explaining:
![Без названия4_20230531110849](https://github.com/bk138/droidVNC-NG/assets/124284281/9576a04f-27d3-4d1e-b174-23d783f2b637)

**Comment by bk138** [comment]
Thanks for the suggestion! What's the intended benefit of this feature? (droidVNC-NG works in Android's standard touch mode, so there's no concept of a cursor position per-se and you can see you local cursor's position anyway...)

**Comment by simpleuserdontwatch** [comment]
It will work like when vnc cursor moves it will show an mouse image at the position of vnc mouse pointer

**Comment by bk138** [comment]
> It will work like when vnc cursor moves it will show an mouse image at the position of vnc mouse pointer

OK, but I think one would see the cursor position anyway by looking at the client's local cursor? :-)

**Comment by bk138** [comment]
Then I don't see so much benefit in it :-)

**Comment by simpleuserdontwatch** [comment]
Wait what? It could be usefull if you wanna to see where do mouse cursor pointing at, and it could be usefull for a explanation too!

**Comment by Simasremmie** [comment]
Hmm? That would be a good idea to add mouse pointer.
