### ISSUE TITLE
x2vnc support?

### ISSUE THREAD

**Issue by beville** [bk138/droidVNC-NG#142]
Very cool project!

This might not be a viable idea, but it would be cool your if server could be used with x2vnc (https://fredrik.hubbe.net/x2vnc.html).

x2vnc lets you use any live VNC screen as a second (or nth) screen.  

Idea would be a move my (Linux desktop) mouse down to my phone (on a stand below my primary monitor) and drive the phone on its screen.  This would mean you'd want to show the mouse cursor, which may not be doable without a physical mouse.

**Comment by bk138** [comment]
Thanks for the props! The server is actually already usable w/ x2vnc _and_ you might want to check outhttps://github.com/bk138/multivnc#multivnc-for-desktop which has x2vnc-functionality built in :-)

For the mouse cursor part, please see #137 for which this is an actual valid use case.
