### ISSUE TITLE
Can't send inputs to target android device.

### ISSUE THREAD

**Issue by jlark9214** [bk138/droidVNC-NG#144]
**Describe the bug**
Quite simply, inputs from the computer do not transfer to the android device I'm trying to control, the screen shares perfectly, the mouse cursor is shown but does not work to click on anything at all. Keyboard inputs are the same.

I've read around and discovered (possibly) that my device not having the uinput module could be causing this problem. Not really sure if anything can be done about this but here's hoping I'm totally off base.

**To Reproduce**
1. Start server
2. Connect with VNC viewer.
3. Click/send keystrokes and nothing happens on the target device.

**Expected Behavior**
Expected to be able to control the android target device.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: 13
 - Client-side OS and version: Windows 10/ Ubuntu  22.04.2 LTS
 - VNC client and version: Tried multiple Viewers, they all had the same issue 

**Additional context**
I even tried a few VNC clients from an Android phone to try and control the target android device with the same results.
Also, the target device is running LineageOS 20 if at all relevant

**Comment by bk138** [comment]
Do you have the accesibility service enabled (the one the app asks you about on startup)?

You can also try alphavnc.

Other than that, it's probably a device issue, not much we can do in this case.

**Comment by jlark9214** [comment]
I did enable accessibility, I also ended up trying anydesk team viewer and another vnc, think your right about it being the device sadly as none of those can control the device either.

**Comment by bk138** [comment]
You might want to try with another ROM 🤔. Closing this one then.
