### ISSUE TITLE
droidVNC-NG disconnects sometimes after login

### ISSUE THREAD

**Issue by rnveach** [bk138/droidVNC-NG#146]
**Describe the bug**

VNC clients sometimes get booted after trying to connect to droidVNC-NG 1.4.0. I don't get an invalid password error. It is basically just drops the connection. I get this when either I put in my password correctly or not. It doesn't always happen. After this happens, I can turn right around and reconnect and it always passes with no issues.

**To Reproduce**
Install droidVNC-NG 1.4.0 from the playstore.
Setup droidVNC-NG and get all permissions granted.
Set a password on droidVNC-NG.
Download tightvnc Java 2.8.3.
Have tightvnc connect to droidVNC-NG.
Provide correct password to log in.

Gets disconnected sometimes after providing password.

**Expected Behavior**

Expected to be able to connect to the device with droidVNC-NG 1.4.0 when provided the correct login.

**Logs/Backtraces**

Will provide the next time it happens. I thought I saved data the last time but it was not contained in the log when looking back.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: Pixel 6, Android 13
 - Client-side OS and version: Windows 10
 - VNC client and version: tightvnc Java 2.8.3

**Additional context**

Usually I can tell this is happening because there is a longer delay before VNC asks for my password then when it doesn't happen.

This issue has occurred before this version, but it didn't always use to happen.

To me it feels like a warm up issue. Like it waits for a long time of no usage and then only occurs once and is good for a bit afterwards.

**Comment by rnveach** [comment]
TightVNC log:
````
[Console output redirected to file:O:\output.txt]
Manifest file not found
Jun 29, 2023 11:19:18 AM com.glavsoft.viewer.Viewer <init>
INFO: TightVNC Viewer version null
Jun 29, 2023 11:19:20 AM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground
INFO: Trying to connect to 192.168.1.165:5901
Jun 29, 2023 11:19:20 AM com.glavsoft.viewer.swing.SwingNetworkConnectionWorker doInBackground
INFO: Connecting to host 192.168.1.165:5901
Jun 29, 2023 11:19:21 AM com.glavsoft.viewer.swing.ConnectionPresenter successfulNetworkConnection
INFO: Connected
Jun 29, 2023 11:19:21 AM com.glavsoft.viewer.swing.SwingRfbConnectionWorker doInBackground
INFO: Handshaking with remote host
Jun 29, 2023 11:19:21 AM com.glavsoft.rfb.protocol.handlers.Handshaker matchProtocolVersion
INFO: Server protocol string: RFB 003.008
Jun 29, 2023 11:19:21 AM com.glavsoft.rfb.protocol.handlers.Handshaker handshake
INFO: Set protocol version to: 3.8
Jun 29, 2023 11:19:21 AM com.glavsoft.rfb.protocol.handlers.Handshaker auth37_38
INFO: Security Types received (2): [2, 16]
Jun 29, 2023 11:19:21 AM com.glavsoft.rfb.protocol.handlers.Handshaker selectAuthHandlerId
INFO: Security Type accepted: TIGHT_AUTHENTICATION
Jun 29, 2023 11:19:26 AM com.glavsoft.viewer.swing.SwingRfbConnectionWorker done
SEVERE: Connection Error : java.io.EOFException, possible reason: remote host not responding.
Jun 29, 2023 11:19:28 AM com.glavsoft.viewer.Viewer closeApp
INFO: Connection cancelled.
````

droidVNC log (search on VNC):
![image](https://github.com/bk138/droidVNC-NG/assets/5427943/3046e8e3-515a-4fc4-af28-1bf30a672b2c)

**Comment by bk138** [comment]
Logcat output from the server side is badly needed here.

**Comment by rnveach** [comment]
Isn't that the screenshot I provided at https://github.com/bk138/droidVNC-NG/issues/146 ? Let me know what I am missing.

**Comment by bk138** [comment]
Sorry I was just glancing over this and kinda expecting a very long log dump. But this is informative as well! It seems that both sides did an orderly shutdown; the server error hints at a network cause (https://stackoverflow.com/questions/2126607/official-reasons-for-software-caused-connection-abort-socket-write-error).

I could not find out any more :man_shrugging:

**Comment by bk138** [comment]
@rnveach are you able to move to another network and see if the issue persists there as well?

**Comment by rnveach** [comment]
I will close it for now. I didn't think this was a network issue, but it hasn't really happened again.

**Comment by bk138** [comment]
OK, dont hesitate to post new info here once available!
