### ISSUE TITLE
No mouse/keyboard input, except navigation button shortcuts

### ISSUE THREAD

**Issue by dset0x** [bk138/droidVNC-NG#147]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
No mouse and keyboard input is accepted by droidVNC-NG on my Galaxy M31 (stock ROM).
**Strangely, Ctrl-Shift-Esc, Home, and Esc work**

**To Reproduce**

1. Accept all required permissions.
2. Connect and try clicking or typing text.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: 12
 - Client-side OS and version: Void Linux
 - VNC client and version: Remmina and tigervnc

**Comment by dset0x** [comment]
Rebooting the phone appears to have resolved the problem.

I also did `adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService:$(adb shell settings get secure enabled_accessibility_services)`, before rebooting. Unsure if it was relevant.

**Comment by bk138** [comment]
Yeah, for keyboard, see #4.
