### ISSUE TITLE
Vnc draws screen very slow

### ISSUE THREAD

**Issue by simpleuserdontwatch** [bk138/droidVNC-NG#148]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

**To Reproduce**

1. Setted scale to 100%
2. connected

**Expected Behavior**

I excepted that it would display without problems but it was drawing screen very slow like line by line

**Your environment (please complete the following information):**
 - droidVNC-NG version: lastest
 - Android version: 10
 - Client-side OS and version: ?
 - VNC client and version: Realvnc ?

**Comment by bk138** [comment]
* please post some logcat output
* have you tried with another device?
* have you tried with another wifi?

**Comment by simpleuserdontwatch** [comment]
It works normally, but in vnc server it draws screen slowly line by line, it's not my WiFi problems its maybe something with app.

**Comment by simpleuserdontwatch** [comment]
But If I set scale to 25% or something it works fastly

**Comment by bk138** [comment]
Please check with another device, the app is known to work on quite a lot.

**Comment by simpleuserdontwatch** [comment]
> Please check with another device, the app is known to work on quite a lot.

I dont have any other device.

**Comment by bk138** [comment]
It's rather improbable that it's an app bug as the server is known to work on a wide variety of devices, so it's rather something in the interaction with the device? What model are you using, is there anything different from other devices?

**Comment by bk138** [comment]
Tentatively closing, please post again here once there's new info.
