### ISSUE TITLE
Screen Capturing permission revoked after reboot

### ISSUE THREAD

**Issue by JanNowakPL** [bk138/droidVNC-NG#149]
**Describe the bug**
At first everything worked fine: I installed an app (droidVNC-NG, ver. 1.4.0), went through initial setup (incl. setting the port, user, password and granting necessary permissions). I tested the connection on many different devices where I have VNC Viewer installed and everything was working flawlessly... unit first reboot of a device where droidVNC-NG is installed. After a reboot I was not able to connect again due to an error: _The connection was refused by the computer_. When I took a closer look directly into the rebooted device I realised that 'Screen Capturing' permission is now disabled and presented in red color in droidVNC-NG app. To sum up, it looks like restarting the device results in revoking 'Screen Capturing' permission and sadly it also makes it not possible to connect remotely to this device again.

**To Reproduce**
1. Perform initial setup of droidVNC-NG and connect successfully using the other device.
2. Reboot the device where droidVNC-NG is installed.
3. Try to connect again.
4. Problem encountered.

**Expected Behavior**
1. I'd expect to be able to connect again to a device where droidVNC-NG is installed also after a reboot.
2. I'd expect to have the 'Screen Capturing' permission not revoked after a reboot.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: 7.1.2 and several other, also newer (tested on multiple devices)
 - Client-side OS and version: MacOS 12.5, Andorid 11 and several other (tested on multiple devices)
 - VNC client and version: 6.21.1109 (MacOS), 4.5.0.49945 (Android)

**Comment by bk138** [comment]
Are you aware of the 2nd bullet point in https://github.com/bk138/droidVNC-NG#notes ?

**Comment by bk138** [comment]
Tentatively closing this, please post again if there's new info.

**Comment by JanNowakPL** [comment]
Hello @bk138 - will you be so kind and reopen this issue? I'd like to post a new comment. Thank you.

**Comment by bk138** [comment]
Oh, I thought one could comment on closed ones.

**Comment by JanNowakPL** [comment]
@bk138 Thank you. Now I can see that it was more about moving the thread between sections (Open vs Closed) :)

In the meantime I managed to solve this problem by executing mentioned ADB commands. I failed on the first try as some debugging options were disabled on the phone side but eventually I succeeded in enabling them and then everything worked perfectly.

Thanks a lot for your suggestion!
