### ISSUE TITLE
Do not work -- connection fail

### ISSUE THREAD

**Issue by luweitest** [bk138/droidVNC-NG#150]
**To Reproduce**
1. open the app
2. give the permissions
3. connect from PC
4. connection fails after about 20s
5. connection to a listening viewer fails too.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: 12
 - Client-side OS and version: Windows XPSP3
 - VNC client and version: TightVNC 2.8.81 and 1.3.10

**Comment by luweitest** [comment]
"telnet 192.168.0.191 5900" do not connect. Port is not open.

**Comment by bk138** [comment]
Thanks for your report! We need server side logcat logs, do you know how to get those?

**Comment by bk138** [comment]
Also, does pinging the device still work while telnet doesn't?

**Comment by bk138** [comment]
Tentatively closing, please post here in case there is new info.

**Comment by luweitest** [comment]
I have updated to 2.1.1 and can not reproduce it now. The only obstacle now is keyboard input.
