### ISSUE TITLE
Cannot update from 1.3.5 to 1.4.0

### ISSUE THREAD

**Issue by freebrowser1** [bk138/droidVNC-NG#151]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
Update to version 1.4 from 1.35 does not work. Signature problem.
I downloaded it then from Github, but same issue occurred.
Obviously, sideloading is enabled on my device.

**To Reproduce**
1. Update the APK from f-droid.org.

**Expected Behavior**
It should update.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.4.0
 - Android version: 10
 - Client-side OS and version: N/A
 - VNC client and version: N/A

**Comment by bk138** [comment]
Didn't change anything in that respect. Does uninstall and then install work for you?

**Comment by freebrowser1** [comment]
That worked, but an upgrade should work as well.

And text entry is still not possible. Typing text does not respond.

**Comment by bk138** [comment]
If you can reproduce the issue, you should maybe open a bug at fdroid, not much we can do about it here.

Your other observation is #4
