### ISSUE TITLE
An overview of the "Latest apps", the "Home" button and the "Back" button.

### ISSUE THREAD

**Issue by paolosezart** [bk138/droidVNC-NG#154]
I'm sorry, maybe I just didn't see it. But when controlling from a PC ---> Android, which keys on the PC keyboard are responsible for handling of special keys to trigger 'Recent Apps' overview, Home button and Back button?
And the same question when running Android ---> Android

**Comment by bk138** [comment]
Hi! No problem, but please use the community chat as outlined in the readme for future questions.

The keys are home, escape and Ctrl-shift-esc, as described in the admin panel.
