### ISSUE TITLE
Black screen, Repeating Frames

### ISSUE THREAD

**Issue by Dingo88** [bk138/droidVNC-NG#156]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

Anytime I connect, it shows a black screen with an infinite amount of frames that just keep repeating. Tried different hosts, same thing. 

**To Reproduce**

**Expected Behavior**

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - droidVNC-NG version:
 - Android version:
 - Client-side OS and version:
 - VNC client and version:

**Additional context**

**Comment by bk138** [comment]
Please also see #114, #35 if they are like your issue.

**Comment by Dingo88** [comment]
![Screenshot_20230801_095534_RVNC Viewer.jpg](https://github.com/bk138/droidVNC-NG/assets/106507771/32d5c7b0-20be-4337-a14d-94f2f7120465)

This is what I get when I connect

**Comment by bk138** [comment]
Just to be sure: you're having server and client on different devices? What happens with another client?

**Comment by Dingo88** [comment]
Look I gotta be honest here, I'm still really new at all this, I don't
honestly understand what that means. I was just looking for a way to run
executable files on Android and I got stuck in a rabbit hole. I saw a way
to run a windows environment on my galaxy s22 and I bit. So truth be told,
I have no idea what I'm doing

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***

**Comment by bk138** [comment]
No problem! I can a) maybe help with your challenge (but need more info for this ) or b) we can consider this issue solved. Which one would you like?

**Comment by bk138** [comment]
OK, me too ;-). Please scan our conversation for my questions and provide some answers, I don't really have the whole picture.

**Comment by Dingo88** [comment]
So I'm running termux as my Linux emulator. I downloaded a slimmed down
version of Ubuntu and Kali Nethunter and 2 different VNCs. The goal has
been and continues to be I want to root this Galaxy. Along the way I found
Metasploit and Hakku framework, and I got interested in pen-testing. And I
still am. Alot of these programs require root access, so I've been here
beating my head against the wall trying to root this phone.

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***

**Comment by bk138** [comment]
I need these tech details to be able to help you:

 * You're having server and client on different devices?
 * What happens with another client?
 - droidVNC-NG version?
 - Android version?
 - Client-side OS and version?
 - VNC client and version?

**Comment by Dingo88** [comment]
Is the server and client supposed to be on different devices?

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***

**Comment by Dingo88** [comment]
droidVNC-NG 1.4.0
Android 13
Both sides are running in chrome developers mode. this laptop is running
the canary channel version of chrome os

**Comment by Dingo88** [comment]
If I run the server and client on Seperator devices it says the port on
which this computer is listening can't be contacted

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***

**Comment by bk138** [comment]
The droidVNC-NG server mirrors the screen of the device its running on. So, if you run a vnc viewer on the same device, you get kind of a infinite mirror effect like so 
![image](https://github.com/bk138/droidVNC-NG/assets/80450/327b21ea-ac6f-4ffd-907a-431537c6e445)

That is expected.

**Comment by Dingo88** [comment]
Ok, thanks for the clarification.

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***

**Comment by bk138** [comment]
Alright, closing then.

**Comment by Dingo88** [comment]
Thank you for your help, I greatly appreciate it.

Steve Chaney
Recovery Technician
Transformation House Inc
1410 S. Ferry Rd
Anoka, MN 55303
612-479-3505 (Mobile)
763-452-7009 (Work)
***@***.***
***@***.***
