### ISSUE TITLE
Copy Configfile to <external files directory>/Android/data/net.christianbeier.droidvnc_ng/files/

### ISSUE THREAD

**Issue by guzzzi** [bk138/droidVNC-NG#165]
Hello,
first of all I want to apologize, I am not so sure in the subject of Android. Currently I am trying to install a Zebra mobile scanner (MC33ax) with DroidVNC, which also works without problems. Now I would also like to give a Config but I can probably no longer write to the path /sdcard/Android/data/net.christianbeier.droidvnc_ng/files/ from Android 11. 
Does anyone have a tip?

Thank you in advance

**Comment by bk138** [comment]
Hi, please use the chat for asking questions, as outline in the README: https://github.com/bk138/droidVNC-NG#readme :-)

Quick answer though: you need to use `adb push` et. al, see https://www.thecustomdroid.com/adb-push-pull-commands/ for instance.
