### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by jasonenglert2** [bk138/droidVNC-NG#166]
Please add a way to autostart the VPN server when opening the app.

Thank you.

**Comment by bk138** [comment]
Hi! Please have a look at the Intent Interface described at https://github.com/bk138/droidVNC-NG#remote-control-via-the-intent-interface - especially the last part about Broadcast Intents: once started the server send an `net.christianbeier.droidvnc_ng.ACTION_START` broadcast intent; you can then have an automation app listen for this and have it setup your VPN. The README lists some of those automation apps, there might be more.
