### ISSUE TITLE
vnc-server reverse connection

### ISSUE THREAD

**Issue by drewer** [bk138/droidVNC-NG#17]
some vnc-server support a reverse connection to vnc-client  (like: winvnc.exe -connect 192.168.1.5:5900 or better with vnc-repeater winvnc.exe -id:123456 -connect 192.168.1.5:5900) 
i think this would be a great enhancent and your vnc-server to an free teamviewer alternative!

**Comment by romain-marie** [comment]
It would be a nice feature!
Congratulation for this nice application.

**Comment by bk138** [comment]
Contributions very welcome! (I don't have much time these days but am able to review pull requests.)
