### ISSUE TITLE
Too much lag

### ISSUE THREAD

**Issue by simpleuserdontwatch** [bk138/droidVNC-NG#172]
When i connect to my phone through vnc,\
it's lagging, even though if my phone is normal, also my speedtest results are
![image](https://github.com/bk138/droidVNC-NG/assets/124284281/10c75c5f-9024-45b1-937d-77a486949d3f)
I think that is the drawing speed so could you speed it up for a bit?

**Comment by bk138** [comment]
Please try the things listed in https://github.com/LibVNC/libvncserver#achieving-good-performance-on-slow-links and maybe report back what worked.

**Comment by bk138** [comment]
Tentatively closing, please re-open or post here if there's new info available.
