### ISSUE TITLE
Android 14 constantly asks to start recording/casting

### ISSUE THREAD

**Issue by rnveach** [bk138/droidVNC-NG#174]
**Describe the bug**

Android constantly keeps asking to start recording/casting. It seems to happen most when I switch to other apps on the android device or switching portrait/landscape.

**To Reproduce**
Install droidVNC-NG 2.1.4 from the playstore.
Setup droidVNC-NG and get all permissions granted.
Set a password on droidVNC-NG.
Turn droidVNC-NG on.
Switch to other apps on the android or even switch portrait/landscape, without even needing to connect to it from a client computer.
Keep getting asked to start recording/casting.

One best example is switching portrait/landscape in the settings app. I keep getting asked there on the main page without going into any other sub-options.

**Expected Behavior**

Expected once I said to start recording 

**Logs/Backtraces**

N/A

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.1.4
 - Android version: Pixel 6, Android 14
 - Client-side OS and version: Windows 10
 - VNC client and version: tightvnc Java 2.8.3

**Additional context**

I just upgraded my phone to Android 14, and I noticed this issue immediately happening after that. I tried changing battery usage on the app from optimized to unrestricted and didn't see a change in behavior. This was not a problem on 13.

When connected with a client, I have sometimes seen the screen stopped updating but controls were still working, I believe this occurs when the popup has come up.

Since 14 is new, I wanted to bring this up incase it is a compatibility problem and not a bug in 14 itself.

**Comment by bk138** [comment]
Thanks @rnveach, I'll have a look ASAP.

**Comment by bk138** [comment]
Btw, what happens if you do a `adb shell cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow ` once?

**Comment by bk138** [comment]
OK, can repro with an Android 14 emulator. Happens in MainService.onConfigurationChanged()

**Comment by bk138** [comment]
And: found https://developer.android.com/about/versions/14/behavior-changes-14#media-projection-consent which probably is the solution.

**Comment by rnveach** [comment]
> Btw, what happens if you do a 

I didn't get any more prompts when restarting the VNC on the device or when playing with the settings app and rotating.

Is this a permanent change or will it go back on reboot?

**Comment by bk138** [comment]
Permanent AFAIK but just a workaround. I'll publish a proper fix in the coming days.
