### ISSUE TITLE
V 2.1.5 is not available in f-droid store

### ISSUE THREAD

**Issue by RichardBeisser** [bk138/droidVNC-NG#176]
Although v 2.1.5 is available in Playstore for some days, you cannot Download it in fdroid.
Because of different signatures you cannot mix Installations.
Please keep Versions synchron
 Thanks

**Comment by bk138** [comment]
Hi Richard,
That's the way f-droid works. We tag a version here and they take some time to pick it up and build it, see https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository :-)

**Comment by RichardBeisser** [comment]
> https://f-droid.org/en/docs/FAQ_-_App_Developers/#ive-published-a-new-release-why-is-it-not-in-the-repository 

Danke für die Erläuterung.
2 Verständnisfragen hätte ich noch:

Habe ich das richtig verstanden dass man als Entwickler dann nur sein Github-Repository bei F-Droid anmeldet, und den Rest macht dann F-Droid selbst?
Die schauen dann in jedem Repo einmal nach ob ein neuer Quellcode commited wurde, und dann holt sich F-Droid den Quellcode und kompiliert selbst daraus die App?


Weil es mich noch betrifft da ich 32-bit-Geräte (arm-v7a) habe:
Baut F-Droid automatisch eine  arm64-v8a, armeabi-v7a, x86 und x86_64 Version, oder steuert das der Entwickler?

Vielen Dank schonmal für die Erläuterungen.

**Comment by bk138** [comment]
Hi Richard,
Ja, die haben einen Service, der periodisch die Repos nach git tags checkt und das dann pullt und baut, alles in deren Infrastruktur. Die verschiedenen Architekturen werden automatisch gebaut, ja.

**Comment by RichardBeisser** [comment]
Danke für die schnelle Rückmeldung.
Ich weiß, es ist nicht dein Thema, aber vielleicht weißt du das auch.
Ich habe im Fdroid-Client die Option gesehen dass man Apps ausschließen kann deren Quellcode nicht öffentlich ist. Daraus schließe ich im Umkehrschluss dass es solche Apps in fdroid gibt.
Schließt sich das nicht gegenseitig aus? Bei fdroid kann man nur mitmachen wenn man ein github-repo hat. Und github-repo bedeutet dann zwangsläufig auch Quellcode offen.

Wegen eigentlichem Thema:
Heute hat fdroid deine neue Version gefunden:
https://monitor.f-droid.org/builds/needsupdate
Dann wird die neue Version denke ich noch diese Woche als App erscheinen.

**Comment by bk138** [comment]
> Danke für die schnelle Rückmeldung. Ich weiß, es ist nicht dein Thema, aber vielleicht weißt du das auch. Ich habe im Fdroid-Client die Option gesehen dass man Apps ausschließen kann deren Quellcode nicht öffentlich ist. Daraus schließe ich im Umkehrschluss dass es solche Apps in fdroid gibt. Schließt sich das nicht gegenseitig aus? Bei fdroid kann man nur mitmachen wenn man ein github-repo hat. Und github-repo bedeutet dann zwangsläufig auch Quellcode offen.

Das weiß ich nicht.
