### ISSUE TITLE
autostart droidVNC on FireTV

### ISSUE THREAD

**Issue by RichardBeisser** [bk138/droidVNC-NG#177]
Hello,

I am using droidVNC on my FireTV-Stick 4k max.
I installed F-Droid-Store via Sideload, then i installed droidVNC from f-droid normally.
With the [description ](https://github.com/bk138/droidVNC-NG#notes) granting the neccessary rights was no problem.

Problem:
droidVNC has the option "Start on boot".
I suppose this will install a service, right?
It seems that this doesnt work on FireTV.

How can I start droidVNC automatically when FireOS starts?

Thanks.

**Comment by bk138** [comment]
Hi @RichardBeisser ,
Well the start-on-boot feature uses https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED which _should_ be fired by every Android device. Could be that AMZ does it differently. 

* can you provide some logcat output of the device start?
* is there an Android emulator image which I could use to reproduce the issue?
* are there maybe other people with the same problem - what does google say?

**Comment by bk138** [comment]
Just tried with an Android TV emulator (API level 30) as per https://developer.amazon.com/docs/fire-app-builder/use-an-android-tv-emulator.html - works in both direct and delayed start.

**Comment by bk138** [comment]
Tentatively closing, feel free to post new info once available.

**Comment by RichardBeisser** [comment]
> Tentatively closing, feel free to post new info once available.

ich weiß, ich bin noch eine Rückmeldung schuldig.
Dieser Emulator der auf der von dir verlinkten Amazon-Seite erwähnt wird, der ist nicht von Amazon, sondern von Google, oder? Ich befürchte (als Laie) der simuliert einen allgemeinen Android-TV, aber keinen FireTV, zumindest nicht 100%

Wenn ich auf dem FireTV mit der App CPU Info aus Fdroid schaue, dann sagt mir diese:
Android: 9
SDK: 28
Kernel: 4.14.87+

Welche Möglichkeiten hat man bei einem Android ohne Root für einen Autostart?
Ich meine ich hätte mal was gelesen dass eine Anwendung einen entsprechenden Dienst installieren muss. Es ist wirklich eine reine Laien-Vermutung, aber ich könnte mir vorstellen dass Amazon in seinem FireOS nicht beliebige Apps automatisch starten lässt.

**Comment by bk138** [comment]
Hallo Richard,
Ich möchte den Fehler gern beheben, dazu braucht es Log-Ausgaben. Die kann ich mir nicht selbst erstellen, da ich kein FireTV hab und der Emu keinen Fehlerfall liefert (https://github.com/bk138/droidVNC-NG/issues/177#issuecomment-1815371879). Bleibt leider nur noch, dass Du die Log-Ausgaben aufnimmst, https://www.google.com/search?q=logcat%20tutorial%20f%C3%BCr%20anwender%20deutsch ist vielleicht ein Einstieg.
