### ISSUE TITLE
Start server upon app Open

### ISSUE THREAD

**Issue by Sepero** [bk138/droidVNC-NG#178]
**Issue**
We want to start the server remotely, but..

To start the server remotely requires opening the app, then navigating the UI to press the Start button. It is possible to setup starting the with the API and ADB, but this is a time consuming and sightly advanced series of steps to follow.

**Feature Request**
A tickbox that allows Starting the server immediately upon opening the app. Termux has an addon that allows it to launch other apps, so launching droidVNC can immediately start the server. This can eliminate the need for proprietary automation apps like Tasker.

**Comment by bk138** [comment]
Hi @Sepero, you have to understand that the app is divided into frontend and backend. What you see as a user is only the frontend, the backend can be started/stopped independently via the [Intent Interface](https://github.com/bk138/droidVNC-NG?tab=readme-ov-file#remote-control-via-the-intent-interface).

So an immediate start on frontend open is not something we will implement as it can already be done in a more generic and powerful way.

**Comment by Sepero** [comment]
> droidVNC-NG features a remote control interface by means of Intents. This allows starting the VNC server from other apps or on certain events. It is designed to be working with automation apps like [MacroDroid](https://www.macrodroid.com/), [Automate](https://llamalab.com/automate/) or [Tasker](https://tasker.joaoapps.com/) as well as to be called from code.

If I understand this correctly, is there no way to start the server from Termux directly? (Without need of proprietary apps?)

**Comment by bk138** [comment]
Not quite. You don't have to use specific apps, anything that can send ordinary Intents will do.

**Comment by jimjamz** [comment]
What would be the requited intent commands to start and stop the server?

**Comment by bk138** [comment]
> What would be the requited intent commands to start and stop the server?

See https://github.com/bk138/droidVNC-NG/blob/master/README.md#remote-control-via-the-intent-interface

**Comment by Sepero** [comment]
Perhaps you may know of an open source app that can send intents?

**Comment by bk138** [comment]
The ones I know are listed here: https://github.com/bk138/droidVNC-NG/blob/master/README.md#remote-control-via-the-intent-interface
