### ISSUE TITLE
droidVNC 2.1.6 server on Android 13 TV Box "H96Max" 

### ISSUE THREAD

**Issue by bobb16** [bk138/droidVNC-NG#182]
Hi,
no input from the client is possible with droidVNC Version 2.1.6 as server (view only).
Mouse is visible and moving but no action on click... Keyboard does not work neither.

Sincerely, Ulf.

**Comment by bk138** [comment]
Hi Ulf,
Few questions:
- Did it work with an older version?
- Did you enable input via the system settings?

Please note that keyboard only works for a few shortcuts as of now, see #4.

**Comment by bobb16** [comment]
Hi Christian,
I have tried version 2.1.5 with no success. Yes, I have enabled input permission. All permissions are marked green in the droidVNC-NG status panel. I would be happy with just mouse input's ...

**Comment by bk138** [comment]
Hm then that's a bug. Somewhere. I developed TV adaptations on an emulator, there it worked...

Can you please try to:
- get a complete logcat output and/or
- try another remote desktop app to see if it has the same issues? IIRC anydesk has a TV version as well...

**Comment by bobb16** [comment]
Anydesk works with an plugin Anydesk asks for in the first run.
Mouse set to off does not work, I remember. Try it again. How do I get  complete logcat output?

**Comment by bk138** [comment]
https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/ might help, there's lots of other tutorials out there as well.

So currently:
- anydesk :heavy_check_mark: 
- droidvnc-ng :no_entry: 
- alphavnc :no_entry: 
?

**Comment by bk138** [comment]
Tentatively closing, please post new info here when available.
