### ISSUE TITLE
Kiosk/Lockdown mode

### ISSUE THREAD

**Issue by ReedDahle** [bk138/droidVNC-NG#183]
Hello,
I have a very specific but straightforward feature request. My company is using Fully Kiosk to lock down and manage tablets for our employees. We need a vnc solution for remote training/debugging, and we were previously using "start on boot" with a defaults.json file and preventing the user from opening the app. The server does not start reliably (most likely an issue with Fully), and the tablet takes a noticeable performance hit while running. I'd like to add a boolean in defaults.json that, when enabled, will hide all the ui elements except the start/stop button and the label showing the tablet's ip, so the end user cannot see any passwords or make changes to the configuration, just start/stop the server.

I may be able to make this change myself, if this is a pull request you'd accept. However, I'm not very familiar with android studio and app development with java/kotlin in general (we use MAUI/Xamarin), but I did manage to clone the repo, manually hide all the unwanted elements and publish a signed apk.

Please let me know if you would implement this, if I should submit a pull request, or if I should just keep my own fork.

Thanks,
Reed

**Comment by bk138** [comment]
Hi @ReedDahle I guess you'd be better off implementing a small launcher app that uses the [Intent interface ](https://github.com/bk138/droidVNC-NG/blob/master/README.md#remote-control-via-the-intent-interface).

**Comment by bk138** [comment]
Thanks for the support @ReedDahle !
