### ISSUE TITLE
unable to send intents via tasker app

### ISSUE THREAD

**Issue by hernanbozzano** [bk138/droidVNC-NG#184]
i am aware of the Remote Control via the Intent Interface section and i read it many times trying to send intents to control droidVNC with the android app called tasker but unfortunately i have not been able to make it work
![image_93](https://github.com/bk138/droidVNC-NG/assets/58406375/f08add4a-b569-48b9-b723-c2a6e4086112)

clearly, as you can see, i am not an expert with intents and speaking english haha 

does anyone have any idea how to complete this fields correctly? i have been trying in different ways for more than 2 hours without success 
thanks in advance
hernan

**Comment by bk138** [comment]
@hernanbozzano here's what i used for testing, let me know if it works for you

- action-category in menu is system->send intent
- in there:
  - action "net.christianbeier.droidvnc_ng.ACTION_START"
  - extra "net.christianbeier.droidvnc_ng.EXTRA_ACCESS_KEY:<your api key from droidvnc-ng start screen>" (took me a while to figure out how Tasker parses this)
  - package "net.christianbeier.droidvnc_ng"
  - class "net.christianbeier.droidvnc_ng.MainService" 
  - target: service

**Comment by hernanbozzano** [comment]
you sir are awesome! among the 40-50 attemps i did, this was not one of them. thank you very much! by the way, i hope this will help someone in the future!

**Comment by bk138** [comment]
Nice! I'll add it to the README for future Tasker users.
