### ISSUE TITLE
give us an option in settings to turn off the disclaimer once accepted

### ISSUE THREAD

**Issue by iansebryk** [bk138/droidVNC-NG#185]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd like**
whenever the VNC server starts, a disclaimer pops up.  EVERY TIME.  i'd like to accept it and never see it again.

**Describe alternatives you've considered**
please give us the option to see it once, accept it and never see it again.  when running an android in kiosk mode and it has to reboot, it should not give the unshaven-unclean and opportunity to kill your VNC server, thus killing your remote access.  having this option would prevent that while still satisfying the legal CYA requiring the disclaimer to begin with.

**Your environment (please complete the following information):**
 - droidVNC-NG version:  2.1.6
 - Android version: 10+
 - Client-side OS and version:  irrelevant
 - VNC client and version:  irrelevant

**Comment by bk138** [comment]
Hi @iansebryk thanks for your feedback. Which disclaimer are you referring to? Can you post a screenshot maybe?

**Comment by bk138** [comment]
Tentatively closing, please post here once you have new info.
