### ISSUE TITLE
Question: Recommendation for viewer for Android and Linux

### ISSUE THREAD

**Issue by Smojo** [bk138/droidVNC-NG#186]
Great App - works perfect and I use it to support a family members phone remotely.

I saw TightVNC as a recommendation as Viewer App on the other (client) end. (at least listed here: https://github.com/bk138/droidVNC-NG#features )

**Do you also have a recommendation for a viewer app for Android and Linux, which works best with droidVNC-NG?**

I used MultiVNC ( https://f-droid.org/en/packages/com.coboltforge.dontmind.multivnc/ ) up to now, but when I'm on my Android device idk e.g. how to touch and hold the notification bar to pull it down.

Maybe not the right place to ask, but I though you eventually know that or have a recommendation.
I would assume that not everybody connects from a Windows system.

**Comment by bk138** [comment]
Thanks for the heads up! I personally use MultiVNC for Android and Linux (because I wrote them and they're kind of done in the way I would want them to be), other very good clients are AVNC (for Android) and Remmina (for Linux). HTH!

**Comment by Smojo** [comment]
> I personally use MultiVNC for Android and Linux (because I wrote them

I saw that MultiVNC is from you as well 5 minutes after I posted this question. ^^

So in the Android (MultiVNC as Viewer) to Android (droidVNC-ng as Server) case, how can I touch and "hold" so that I can swipe something from a to b (like pulling down the notification bar / open the notification drawer)?

**Comment by bk138** [comment]
I've never used both tools together, but I guess your best bet is to hold the left virtual mouse button in MultiVNC, move the cursor down and release again. Enabling cursors in droidVNC-NG might help!

**Comment by Smojo** [comment]
Ok it even works without the mouse. You just have to ensure that the left mouse button is really activated - red color (and stays like that). Then pull down by moving the round circle from top to down. Still is feels a bit slowish.

Anyway no need to discuss this further - will close this issue. Great Apps - keep it up! ;-)
