### ISSUE TITLE
Ability to send 'power button press'

### ISSUE THREAD

**Issue by csm10495** [bk138/droidVNC-NG#187]
**Is your feature request related to a problem? Please describe.**
I was trying to figure out how to press the power button via vnc, and couldn't figure it out.

**Describe the solution you'd like**
A shortcut or some sort for it.

**Describe alternatives you've considered**
Just logging out of VNC.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.1.7
 - Android version: 14
 - Client-side OS and version: Win 10x64
 - VNC client and version: TightVNC Viewer 2.8.81

**Comment by bk138** [comment]
Hi @csm10495 that might be doable via Android's a11y API, but what effect do you want to achieve in the end? Power off the device or just the screen?

**Comment by csm10495** [comment]
Just the screen. Though it might be nice to be able to hold it to get to the restart button.
