### ISSUE TITLE
Wrong resolution on external Display (1920x1080 landscape)

### ISSUE THREAD

**Issue by 5A52** [bk138/droidVNC-NG#188]
**Describe the bug**
Runing droidVNC-NG on external display reports wrong resolution to viewer

**To Reproduce**
Needs external monitor

Ill try to explain with screenshots. 
Screenshots are from RVNC on another android phone because RVNC reports server resolution, but behavior is the same on any viewer, even on PC

**Viewer in portrait mode**
![Screenshot_20240128-125550_RVNC Viewer](https://github.com/bk138/droidVNC-NG/assets/65124087/a118bb6c-82e5-4e82-a89e-da45f7940d0d)

**Viewer in landscape**
![Screenshot_20240128-125616_RVNC Viewer](https://github.com/bk138/droidVNC-NG/assets/65124087/23ecc8f6-dbe4-4d8f-aa5f-8bd338dda8d5)

**Viewer with server resolution**
![Screenshot_20240128-125626_RVNC Viewer](https://github.com/bk138/droidVNC-NG/assets/65124087/f450c575-50ba-4daa-8f9e-124138ae1312)

**Different VNC server for android**
No idea why it scales down resolution (both, client and server are FullHD) but aspect ratio is correct.
![Screenshot_20240128-125714_RVNC Viewer](https://github.com/bk138/droidVNC-NG/assets/65124087/dd39d253-206c-4602-b96b-4c36bf0a09b8)

P.S. Input works, but sends touches to main phone display

**Comment by bk138** [comment]
Thanks for reporting!
Two thoughts:

- Have you tried with another viewer?
- Is this something that can be reproduced with an emulator? How is the screen attached?

**Comment by 5A52** [comment]
1 - yes, bVnc on android and reminna arch on a PC. I mentionned up there, screenshotst are from RVNC only because RVNC reports server resolution.
2 - I believe yes, if emulator emulates "secondary displays". It is also possible to simulate it from android Developer options, but simulating on a main display is a real mess. 
My screen is a HDMI attached to samsung note 9 phone.

**Comment by bk138** [comment]
I don't have an MHL cable so if ever can only repro this w/ the emulator. Detailed steps of how one is able to reproduce this w/ the emulator would help a lot!

**Comment by 5A52** [comment]
Sorry Im not using emulator, unfortunatelly  not a developer at all, but may be this will help:
https://innovorder.dev/multi-screen-management-within-android-56ef9052f066
or this
https://source.android.com/docs/setup/create/cuttlefish-multi-display
Also I dont know how droidVNC-NG code gets display resolution/aspect ratio/etc, but I can provide any log or other information from a physical hardware if you need. Like for example android reports my displays as:

# wm size -d 0
Physical size: 1440x2960
# wm size -d 2
Physical size: 1920x1080

**Comment by bk138** [comment]
Maybe you can try and download Android Studio which includes an emulator and try to reproduce. I can't fix this as I don't have the MHL/HDMI hardware and need another reproduce case.

**Comment by 5A52** [comment]
Sorry, I can not install android studio on an android phone (yes im using a phone as a desktopPC). I believe you will easely reproduce the bug with emulator if you need, just chose any landscape aspect ratio for secondary display.
As I mentioned on 4th screenshot "Alpha VNC Lite" which is Android VNC server also, does not have this bug.

**Comment by RaulMerelli** [comment]
I have some resolution issue, the screen is vertical 800x480 px, but seems to appear almost a square (800x770), with a black band on right. Tried with RealVNC and UltraVNC as viewers. When the screen is horizontally rotated, the black band on the right is smaller (resolution 830x480). Looking on ADB is correctly reporting the original screen resolution: Display DisplayDeviceInfo{"droidVNC-NG": uniqueId="virtual:net.christianbeier.droidvnc_ng,10230,droidVNC-NG,0", 480 x 800, modeId 4, defaultModeId 4, supportedModes [{id=4, width=480, height=800, fps=60.0, alternativeRefreshRates=[]}], colorMode 0, supportedColorModes [0], hdrCapabilities null, allmSupported false, gameContentTypeSupported false, density 240, 240.0 x 240.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, deviceProductInfo null, state ON, committedState UNKNOWN, owner net.christianbeier.droidvnc_ng (uid 10230), frameRateOverride , brightnessMinimum 0.0, brightnessMaximum 0.0, brightnessDefault 0.0, FLAG_PRIVATE, FLAG_PRESENTATION, installOrientation 0}

**Comment by bk138** [comment]
@RaulMerelli i think you're experiencing #145 actually?

**Comment by RaulMerelli** [comment]
@bk138 Sorry, I didn't see that there was this specific issue. Seems exactly the same problem.

**Comment by bk138** [comment]
> @bk138 Sorry, I didn't see that there was this specific issue. Seems exactly the same problem.

But you're seeing an extreme form...

**Comment by RaulMerelli** [comment]
> > @bk138 Sorry, I didn't see that there was this specific issue. Seems exactly the same problem.
> 
> But you're seeing an extreme form...

Quite a big margin in fact:
![image](https://github.com/bk138/droidVNC-NG/assets/13584954/a571297e-8be2-4739-9576-aa99863536c1)

480x800 could be a particular screen resolution.

**Comment by bk138** [comment]
@5A52 I have a customer with a similar problem. Which Android version are you using?

**Comment by 5A52** [comment]
> @5A52 I have a customer with a similar problem. Which Android version are you using?

Android 12,13,14. But all of them samsung oneui (4.1,5.1,6.1,6.1.1).
Issue does not hurt me, as input does not work anyway on second display. But if you need I can collect logs, or any other information.

**Comment by bk138** [comment]
@5A52 As the the issue does not hurt you and the situation w/ my customer turned out to be an OEM bug, I'll document secondary display support and close this.
