### ISSUE TITLE
Old Android

### ISSUE THREAD

**Issue by kayden25** [bk138/droidVNC-NG#189]
Should add support for older versions of android if that's possible, specifically Android KitKat 4.2.2

**Your environment (please complete the following information):**
 - Android version: 4.2.2
 - Client-side OS and version: 12

**Comment by bk138** [comment]
Unlike #56, this is not easily possible, as it requires hidden root-needing API. You might want to stick to  https://github.com/oNaiPs/droidVncServer for these Android versions.
