### ISSUE TITLE
Input Permissions Denied, no option to allow

### ISSUE THREAD

**Issue by sha120120** [bk138/droidVNC-NG#190]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
Installed App onto an Android box. All permissions are granted except Input permissions. There is no prompt, I cannot find input permissions on the settings of the app and permissions settings.

**Comment by bk138** [comment]
@sha120120 thanks for reporting. The prompt  UI you are referring to is part of the Android OS, usually found somewhere in Settings. If that is missing on your device, you should consult your OEM.

Which Android version are you running on what kind of device?

**Comment by bk138** [comment]
Tentatively closing, please post here once new info is available.
