### ISSUE TITLE
Build Issues on Windows with Android NDK and CMake

### ISSUE THREAD

**Issue by world9604** [bk138/droidVNC-NG#192]
**Describe the bug**
I'm attempting to integrate the droidVNC-NG library into my Android app on Windows, following successful builds on Ubuntu. However, I encounter a build error on Windows stating a failure to fingerprint input file property due to a missing 'libdroidvnc-ng.so.dbg' file. I'm seeking advice on configuring my Windows PC development environment correctly to resolve these build errors and ensure compatibility with the Android NDK and CMake.

**Your environment (please complete the following information):**
- os : windows 11
- gradle version : 7.6
- ndk : 23.1.7779620

**To Reproduce**
1. git clone
2. git submodule update --init
3. .\gradlew assembleRelease
4. build error log  : "Failed to create MD5 hash for file 'E:\develop\etc\droidVNC-NG\app\build\intermediates\native_debug_metadata\release\out\arm64-v8a\libdroidvnc-ng.so.dbg' as it does not exist."

**Expected Behavior**
1. git clone
2. git submodule update --init
3. .\gradlew assembleRelease
4. build success!!

**Comment by bk138** [comment]
Please use the [community chat](https://gitter.im/droidVNC-NG/community) for future questions :-)

I'm not building on Windows so have no info on the build setup there. Your best bet might be to research around Android Studio, CMake and Windows. It looks like your release build is looking for files related to the debug build which seems flaky. Maybe doing a `git clean -fxd` before building might help?

Sorry for not being able to help you on this one.
