### ISSUE TITLE
How can I connect to two android devices when them are not in same local area network?

### ISSUE THREAD

**Issue by banboybanban** [bk138/droidVNC-NG#193]
Dear Developer

I am writing to confirm that whether the droidVNC supports that has a connection between 2 android devices when they are not in the same local area network?

I think it's necessary for me to have a "VNC repeater" to reach my goal, but I didn't know  which "VNC repeater" should I have a try
Could you give me some suggestion?

Thanks a lot

**Comment by bk138** [comment]
Dear @banboybanban, please use the [community chat](https://gitter.im/droidVNC-NG/community) for future questions :-)

You can follow two approaches:
- have  both devices dial out from their LAN to a [repeater](https://www.google.com/search?q=vnc+repeater) which acts like a rendezvous point
- or have the server part exposed to the Internet, see https://github.com/bk138/droidVNC-NG?tab=readme-ov-file#for-accepting-connections-from-outside for this

HTH!

**Comment by banboybanban** [comment]
Dear @bk138 

So thanks for you instantly reply.
I am able to access to the [community chat](https://gitter.im/droidVNC-NG/community) but I can't login in successfully, so I can't add any comment in community chat. So I have to add comments here and below is my query.

I am trying to establish a VNC repeater and find "Ultra VPN repeater" may be a selection.
I want to know if "Ultra VPN repeater" can work well with droidVNC? Or do you have any other recommended repeater for me?


Thanks

**Comment by bk138** [comment]
Yes that is pretty much the only one, there's a Linux version as well. The server works with this.
