### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by oxr463** [bk138/droidVNC-NG#20]
See: https://gitlab.com/fdroid/rfp

**Comment by bk138** [comment]
No objections from my side. Are you going to publish the app there?

**Comment by Mannshoch** [comment]
any news on this?

**Comment by oxr463** [comment]
I forgot to file it. I just completed it, https://gitlab.com/fdroid/rfp/-/issues/1773

**Comment by DJCrashdummy** [comment]
jfi: the [RFP is closed](https://gitlab.com/fdroid/rfp/-/issues/1773#note_cfa4fc8cd30054385848f4af8b10e877450647a9) and the [app is in the repo](https://f-droid.org/en/packages/net.christianbeier.droidvnc_ng/). :+1:
