### ISSUE TITLE
Viewing video of a channel from Android TV 11

### ISSUE THREAD

**Issue by Johpin1** [bk138/droidVNC-NG#201]
**Is your feature request related to a problem? Please describe.**

When using TigerVNC on a Raspberry Pi the contents of a television channel from an Android TV will not be shown. No video, no sound, only the info banner will be shown. For Kodi's addon Retrospect there is also no audio and video. However for the app Youtube the video will be shown.

**Describe the solution you'd like**

Showing the video of a television channel.

**Describe alternatives you've considered**

No alternative available for me.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.2.0
 - Android version: Android TV 11
 - Client-side OS and version: Raspberry Pi OS Bookworm
 - VNC client and version: TigerVNC v1.12.0 (64bit)

Short question: I disabled input, because of safety (no SSL, no waiting time after wrong password). Is it safe to use for WAN in this way?

**Comment by bk138** [comment]
If other apps work, it might simply be that the TV app opted out of being captured by the Android OS, see https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE 

You can try with alphavnc and see if it makes a difference, please post news here.

As for your  WAN question: short answer: not yet. Work is underway for secure WAN access.

**Comment by Johpin1** [comment]
Alphavnc Lite was not available in the Play Store for Android TV. After sideloading it,I saw it gives the same result: no video for tv channels, only the info banner.

Remarkable is that Kodi's Youtube and IPTV Manager addons show video, while the addon Retrospect doesn't.
Using the television as monitor for a computer on HDMI  I see there is only a black screen: no window of the used vncviewer. 

NIce secure WAN access is underway.

**Comment by bk138** [comment]
OK, closing then :wave:
