### ISSUE TITLE
Does not work under Android 14

### ISSUE THREAD

**Issue by freebrowser1** [bk138/droidVNC-NG#202]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
When starting it repeatedly says that accessibility is a restricted setting, even after I enabled it with Apps => ... (top right) => Allow restricted setting.
Then I did:
```
adb shell cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow
adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService:$(adb shell settings get secure enabled_accessibility_services)
```
restarted the app and clicking on Start says I had to allow accessibility which was still restricted despite I did it earlier and allowed the restricted setting.

**To Reproduce**
1. Install the app.
2. See above.

**Expected Behavior**
It should work.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.30
 - Android version: 14
 - Client-side OS and version: I did not come that far.
 - VNC client and version: I did not come that far.

**Comment by bk138** [comment]
Just tried again on Android 14 and works well here - what kind of device are you using?

**Comment by freebrowser1** [comment]
Indeed, I downloaded it from Github.
I use a Nothing phone 2a.

**Comment by bk138** [comment]
OK, then it really might be https://github.com/bk138/droidVNC-NG/issues/135#issuecomment-1566657486 - let's wait a few days once the app is available on the Play Store, would be nice if you could report back then.

**Comment by freebrowser1** [comment]
@bk138: I just found out it worked ! See my previous note.

**Comment by bk138** [comment]
Ah ok, closing then. For the keyboard see #4, it's work in progress.
