### ISSUE TITLE
Remove confirmation at start

### ISSUE THREAD

**Issue by brac321** [bk138/droidVNC-NG#205]
Please remove confirmation at apk starting, so it can run on its own.

Thanks

**Comment by bk138** [comment]
Hi! Please clarify which confirmation you mean. There are some from Android OS that cannot be removed.

**Comment by brac321** [comment]
Running Smart Box X96Q on Android OS. Every time after restart (Smart Box boot) it requests confirmation as shown on picture below. Is that OS request?
![media_20240506_095114_4706508407734552056](https://github.com/bk138/droidVNC-NG/assets/49706441/27f6a0c7-2025-4342-a012-0b2381c266dd)

**Comment by bk138** [comment]
That's from Android, see bullet point 2 in https://github.com/bk138/droidVNC-NG?tab=readme-ov-file#notes
