### ISSUE TITLE
Mouse clicks freeze connection for 1 second each and are not sent (Android 10)

### ISSUE THREAD

**Issue by RayKoopa** [bk138/droidVNC-NG#213]
**Describe the bug**
Client is a PC using a mouse.
Left- or right-clicking or using the mouse wheel in the VNC view completely freezes screen updates for exactly 1 second before they return, and the click is not executed.

The clicks/freezes can be stacked (e.g. attempting to double click freezes for 1 second, refreshes 1 frame, then freezes for another second).

Key presses / shortcuts are submitted and executed as expected.

**To Reproduce**
1. Start droidVNC-NG, enable/allow all required permissions as guided by the app.
2. Connect to droidVNC with VNC client from PC.
3. Click anywhere with any mouse button or scroll the mouse wheel - for every input, the screen freezes for 1 second.

**Expected Behavior**
The screen does not freeze, and the click is executed as a touch input on the server.

**Logs/Backtraces**
Please let me know which logs to retrieve (and how if not trivial, basic adb knowledge available), willing to provide any info as requested.

**Your environment:**
 - droidVNC-NG version: 2.4.0
 - Android version: 10 (latest EMUI build 10.0.0.347) on an Honor X9 device
 - Client-side OS and version: Windows 11 22H2 Education (10.0.22621.3672)
 - VNC client and version: latest TightVNC Viewer 2.8.84 (May 8 2024)

**Additional context**
- UltraVNC viewer has the same issue.
- TeamViewer QS can successfully send mouse inputs as expected.
- This device cannot be rooted.
- Sounds similar to https://github.com/bk138/droidVNC-NG/issues/171

**Comment by bk138** [comment]
Thanks for reporting! Are you able to provide logcat output? That's the only way to know what's happening.

**Comment by bk138** [comment]
Yeah do so! (love these self-closing issues ;-) )
