### ISSUE TITLE
Cannot launch apk files

### ISSUE THREAD

**Issue by Realgigabyte** [bk138/droidVNC-NG#215]
**Describe the bug**
If I launch an .apk I am not able to confirm if I want to install the app.

**To Reproduce**

1. Navigate to an apk file to install via a file manager and launch it.
2. Android shows a prompt window and asks if I want to install.
3. If I try to click on 'confirm' nothing happens, only the 'cancel' button works.
4. If I use a local mouse I am able to click on 'confirm'

**Expected Behavior**

I should be able to confirm the installation via VNC when prompted

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.4.0
 - Android version: 8
 - Client-side OS and version:  Windows 10
 - VNC client and version: ThightVNC

**Additional context**

**Comment by bk138** [comment]
Thanks for reporting. That might be an Android security feature. Can you try with alphavnc and TeamViewer and check if they work?

**Comment by apksack** [comment]
Hi,
It seems you're unable to confirm APK installations via VNC, only via a local mouse. Here are quick steps to troubleshoot:

-Check VNC Settings: Ensure your VNC client forwards all input events correctly.
-Update VNC Client: Use the latest TightVNC version on Windows 10.
-Permissions: Confirm droidVNC-NG has the necessary permissions on Android.
-Try Other Clients: Test with different VNC clients like RealVNC or VNC Viewer.
-System Settings: Check Android's settings for input restrictions.
        Provide logs if needed for further help.

**Comment by bk138** [comment]
@Realgigabyte Were you able to try with  alphavnc and TeamViewer?

**Comment by Realgigabyte** [comment]
@bk138  I tried again with TightVNC and was working on another machine.
I went back on previous machine and realize it was on version 2.2 so I installed version 2.4.1 and is working there too. (Pretty sure wasn't working before for some reasons, sorry for that)

(on another note the file transfer icon is greyed on TightVNC although I enabled File Transfer on DroidVNC)

**Comment by bk138** [comment]
@Realgigabyte so it's working for you now? 

W.r.t. file transfer: TightVNC-2.0-style file transfer is not implemented in libvncserver, see https://github.com/LibVNC/libvncserver/issues/624

**Comment by Realgigabyte** [comment]
@bk138 Yes it seems fine now. I also tried to get out of developer mode to double check and it still let me install apk's.
Thanks a lot.

**Comment by bk138** [comment]
Well I didn't do anything ;-)
