### ISSUE TITLE
Virtual session

### ISSUE THREAD

**Issue by imayoda** [bk138/droidVNC-NG#216]
Hi there, and thank you for your time

May I ask a question: is it possible in actual android code to have a virtual "desktop" server like the one tigervnc creates?
My main goal would be to run android apps with screen off...

Thank you again

**Comment by bk138** [comment]
Yes, that's in principle possible, the question is whether it could be a root-only thing. Please subscribe to #131 for this :-).

**Comment by imayoda** [comment]
ultra faaaast thank you, subscribed
