### ISSUE TITLE
The password configured on the droid-ng VNC interface is not working w/ Guacamole 1.5 client

### ISSUE THREAD

**Issue by luyaotang** [bk138/droidVNC-NG#219]
The password configured on the droid-ng VNC interface is not working. Currently, I've set up the connection in Guacamole, but I found that whether the password is correct or incorrect, or even if no password is configured, the connection to droid-ng VNC still works normally.

![image](https://github.com/user-attachments/assets/60d228f6-9209-4366-b4ff-1d964bbd8cc4)
![image](https://github.com/user-attachments/assets/960cb142-daf0-447c-8b99-57b105b15255)

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.5.0
 - Android version:  Android 14
 - Client-side OS and version: guacamole

**Comment by bk138** [comment]
Thanks for reporting! However, I cannot reproduce this. Is your password some non-ASCII string? Can you try with another client please?

**Comment by luyaotang** [comment]
password is somthing like abc1234

**Comment by luyaotang** [comment]
I tried VNC Viewer, and it indeed is influenced by the password set in droidVNC-NG. Based on the comparison between Guacamole and VNC Viewer, it seems that the password on the VNC server side is just for show. If a malicious client doesn't follow the standard implementation, it can bypass the password and directly connect to the server.

**Comment by luyaotang** [comment]
https://guacamole.apache.org/releases/
![image](https://github.com/user-attachments/assets/e673fa95-cb3c-4fa0-865a-360d8d3734d6)
Sure, here is the translation:

---

## 2. Server Installation

Extract the downloaded `guacamole-server-1.5.1.tar.gz` to any directory. I placed it in the `/opt` directory.

### Install Compilation Environment
```bash
yum install cairo-devel libjpeg-devel libpng-devel uuid-devel ffmpeg-devel freerdp-devel freerdp-plugins pango-devel libssh2-devel libtelnet-devel libvncserver-devel pulseaudio-libs-devel openssl-devel libvorbis-devel libwebp-devel wget gedit java-1.8.0-openjdk* libwebsockets-devel libgcrypt-devel
```

### Extract and Compile
```bash
tar zxvf guacamole-server-1.5.1.tar.gz -C /opt/
cd /opt/guacamole-server-1.5.1
./configure
make && make install
```

### After Installation, Check if `guacd` is Successfully Installed:
```bash
ldconfig
systemctl restart guacd
systemctl enable guacd
systemctl status guacd
```

---

## 3. Client Installation

If using the official client: simply use the downloaded `guacamole-1.5.3.war`. 
systemctl restart tomcat
```


---

## 4  Server Side Configure

### Create the `/etc/guacamole/` Directory:
```bash
mkdir /etc/guacamole/
```

### Create the `guacamole.properties` File:
```bash
[root@zmdev guacamole]# cat guacamole.properties
# Hostname and port of guacamole proxy
guacd-hostname: 127.0.0.1
guacd-port: 4822
user-mapping.xml: /etc/guacamole/user-mapping.xml
enable-clipboard-integration: true
```

### Create the `user-mapping.xml` File in the `/etc/guacamole/` Directory:
```bash
[root@zmdev guacamole]# cat /etc/guacamole/user-mapping.xml
<user-mapping>
        <!-- This configuration will show the device selection page after login -->
        <authorize username="xxxxx" password="xxxxxx">
                <connection name="zk(242)-RDP">
                        <protocol>rdp</protocol>
                        <param name="security">nla</param>
                        <param name="hostname">192.168.22.242</param>
                        <param name="port">3389</param>
                        <param name="color-depth">24</param>
                        <param name="username">xxxxx</param>
                        <param name="password">xxxxx</param>
                        <param name="ignore-cert">true</param>
                        <param name="enable-font-smoothing">true</param>
                </connection>
                <connection name="zk-242(VNC)">
                        <protocol>vnc</protocol>
                        <param name="hostname">192.168.22.242</param>
                        <param name="port">5900</param>
                        <param name="password">xxxx</param>
                </connection>
        </authorize>
</user-mapping>
```
## 4  Login Test
Browser Access:
http://192.168.22.xxxx:xxx/guacamole/

Default Username and Password: guacadmin / guacadmin
After logging in successfully, please change the password.

**Comment by luyaotang** [comment]
let me try on another phone

> I don't know the reason, but regardless of whether I set it up or not, or even if I set it up incorrectly, it can still connect to my phone normally. It is also unrelated to whether I use repeater services. The version of Guacamole is 1.5, the phone is Android 14, and DroidVNC-NG is 2.5.0. ![image](https://private-user-images.githubusercontent.com/16934367/351752410-b7dc75fb-bb50-456b-95ce-d681a0c1284c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzEzMDEsIm5iZiI6MTcyMTgzMTAwMSwicGF0aCI6Ii8xNjkzNDM2Ny8zNTE3NTI0MTAtYjdkYzc1ZmItYmI1MC00NTZiLTk1Y2UtZDY4MWEwYzEyODRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMzZmY2MxYjQwNDkyNmQ1OTM0NTVkZGZlMmRkYzVkNjM0OWY0NDQwZGY3ZjQ1MzY4NDVlY2VjZWYzZWU4ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Trb0DJHxN6Ak9llPJtNJbCmnCioosY4KkPxKqXJ2-K8)
> 
> > That's indeed a bug then, but very probably in the underlying library. How would I be able to repro with Guacamole most easily?
> > Edit: tried with this https://krdesigns.com/articles/how-to-install-guacamole-using-docker-step-by-step tutorial. If I enter a wrong password or none, droidVNC-NG does not let me in, so everything works as expected.

**Comment by luyaotang** [comment]
On other devices, it's the same issue. Regardless of what the password is set to, it can directly connect to DroidVNC-NG.

![image](https://github.com/user-attachments/assets/e01d68ea-d070-4592-b280-aa8a1f53fc1d)

> let me try on another phone
>

**Comment by bk138** [comment]
@luyaotang  Might it be that the password is somehow cached or Guacamole 1.5 has some superpowers? Can you try with my setup https://krdesigns.com/articles/how-to-install-guacamole-using-docker-step-by-step to rule out Guacamole?

**Comment by luyaotang** [comment]
I will try using Docker to build Guacamole later. It should be unrelated to the cache. I also tried changing different passwords in DroidVNC-NG and configuring different passwords in Guacamole, but the result was that I could access it directly, regardless of the password.

**Comment by luyaotang** [comment]
Sorry for the confusion. The issue can be closed. It seems that there is a connection pool between guacd and droidvnc-ng. When reconfiguring the password in the configuration interface, the current connection will not be disconnected, causing the previous connection to be reused during the preview. If I restart droidvnc-ng, the changes can take effect.
