### ISSUE TITLE
[Question] Dealing with Screen Capture permission

### ISSUE THREAD

**Issue by nyash** [bk138/droidVNC-NG#22]
Hello,

I am using this vnc server succesfully on raspberry pi 3 to be able to control/monitor an obscure device that provides access only via an android app. Thank you for this!

However, one inconvinient aspect is that whenever the android system reboots and vnc server autostarts, it asks for the Screen Capture permission by displaying a dialog box.

If the permission is not provided and we connect via VNC only a black screen is displayed. 

Surprisingly despite the black screen, the window reacts to all input events via VNC, so it is acually possible, but difficult to accept the permission by clicking in the right spot. If done, then the black screen goes away and we get to see the desktop.

So my question is this, are there any means of accepting/providing this permission automatically/permanently? 

Unfortunately I am not well versed with Android, but since my device has root access this should be somewhat feasable? (Either some app that can assist with it or system file modifications? or somehow running the vncserver as root?)

-- Android 10 with root (LineageOS 17)
-- Raspberry Pi 3

**Comment by bk138** [comment]
Already closed by d9230bc863b623a1d0a948161bad48316bbfb899, it's in the README
