### ISSUE TITLE
Repeater reconnect not working w/ Guacamole relay

### ISSUE THREAD

**Issue by luyaotang** [bk138/droidVNC-NG#220]
~~1. Clicking "Start Service" does not interact with the already configured connection options under "Connect to Relay Server" below. I hope that if a configuration exists, clicking "Start" should apply it, rather than requiring you to click "Connect to Relay Server" again to trigger the relay service startup.~~
2. Currently, when connecting through the repeater, if the viewer disconnects, the repeater will close both sides of the connection. To use the viewer again, you have to re-trigger the connection by clicking "Connect to Relay Server" in droid-ng VNC. I hope that when the service is already running, droid-ng VNC will maintain its connection with the repeater and handle reconnections automatically.

![image](https://github.com/user-attachments/assets/4d577930-7b58-49d0-8b6b-4cfd8e386406)
From the diagram, it can be seen that when the view exits, both the droid-ng VNC and the viewer connections are closed, which means that the next time the viewer connects, there is no available VNC server. It is needed for droid-ng VNC to maintain a thread that keeps the connection with the repeater active while it is in the "running" state and configured with the relay server.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.5.0
 - Android version: Android 14
 - Client-side OS and version: guacamole
 - VNC client and version:

**Comment by bk138** [comment]
Please don't mix up different issues in the same report. Also, please consider using the chat.

For your first question: "Start" intentionally only starts the server. For further automation, please use the Intent interface lined out in the README.

Your second issue should be handled by #200 which is in v2.5.0.

**Comment by luyaotang** [comment]
I tested this on the latest version 2.5.0, and the second  issue still exists. The testing procedure is as follows:

1. Set up the relay server address on the phone, connect, and a toast message at the bottom indicates a successful connection.
2. Use Guacamole as the viewer to connect; it connects successfully.
3. Close the Guacamole page.
4. At this point, check the relay server logs, which show that both the viewer and the droidVNC-NG server have closed.
5. Attempt to reconnect using Guacamole, but it fails to connect.
6. Return to droidVNC-NG, click on the relay connection, and now Guacamole can connect successfully.

![image](https://github.com/user-attachments/assets/50000795-2470-4234-9d24-91fee552dbdf)

**Comment by bk138** [comment]
@luyaotang As noted in the README, droidVNC-NG supports  UltraVNC-style Mode-2 repeaters only. I've tested this with the uvncrep Linux version and reconnect works there. I'm inclined to think you're trying UVNC mode 1 as Guacamole does not seem to support UVNC repeater mode 2? Can you please share your exact setup (uvnc config and guacamole config)?

**Comment by eric-et** [comment]
Can I reopen this one ? I got the same issue with noVNC as the client and a UltraVNC-style repeater. Every time the client drops the connection to the repeater, the repeater also drops the connection to droidVNC-NG. I wanna my remote phone always accessible so if it will be very handy if droidVNC-NG can keep the connection to a repeater and automatically reconnect.

**Comment by bk138** [comment]
@eric-et feel free to, but as I wrote, it works for me. This is basically only actionable if you share your exact setup :-)

**Comment by eric-et** [comment]
Thanks for the reply.

I didn't see the 'max retry times of reconnection' option in the dialog of 'connecting to a repeater'. I just realize I can set it to a very big number so it will always reconnect. And it works! Thanks!

**Comment by bk138** [comment]
Great! Always happy about a positive review!
