### ISSUE TITLE
Not a bug but mobile network does work with VPN

### ISSUE THREAD

**Issue by freebrowser1** [bk138/droidVNC-NG#221]
**Describe the idea**

Not a bug, but a way to VNC over mobile network to the cellphone using a VPN. VNC is not encrypted in itself, however a VPN (or SSH tunnel) is encrypted.
The documentation states:

_Connect to your local Wi-Fi. For accepting a connection your device should be connected to some Local Area Network that you can control, normally it is a router. 
**Connections via data networks (i.e. your mobile provider) are not supported.**_ 

Well, when using a VPN (a VPN on a server you can control and thus obtain the VPN tunneled ip addresses) or SSH tunnel it is supported.

**To Reproduce**
1. Have OpenVPN app on the phone and an OpenVPN server on e.g. a VPS.
2. Turn Wifi off and turn mobile network on.
3. Connect the Android OpenVPN client to your server.
4. Start DroidVNC and note the OpenVPN tunneled IP address, something like 10.8.0.x (shown in this app).
5. Connect the computer using the VNC client with the same VPN server which gets a similar tun ip address like 10.8.0.y (last number different)
6. Connect from VNC client to ip 10.8.0.x.

In Wireguard I did not test this successfully.

**Comment by bk138** [comment]
Am I right in that you're proposing a wan setup via VPN, not reporting a bug?

**Comment by freebrowser1** [comment]
> Am I right in that you're proposing a WAN setup via VPN, not reporting a bug?

Yes, this is not a bug, but I tell that I could reproduce the VNC connection over mobile internet.

**Comment by bk138** [comment]
OK thanks!
