### ISSUE TITLE
Mouse input does not work without a touch screen connected

### ISSUE THREAD

**Issue by damienwolf07** [bk138/droidVNC-NG#222]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

I am running a Moto G6 Play that is rooted and modified. If I start Android without the touch digitizer connected, Mouse input actions (from droidVNC) do not work. However if I use a Bluetooth mouse (as a temporary workaround) to control, Everything works.

**To Reproduce**

N/A

**Expected Behavior**

I expect for mouse input to function without a touch display connected.

**Logs/Backtraces**

N/A

**Your environment (please complete the following information):**
 - droidVNC-NG version: ``droidVNC-NG 2.5.0``
 - Android version: ``kangos_jeter-userdebug 11 RQ3A.210605.005 b8ffcfff5d release-keys``
 - Client-side OS and version: ``Microsoft Windows 10 Pro``, ``10.0.19045 N/A Build 19045``
 - VNC client and version: ``RealVNC Viewer 7.8.0``

**Additional context**

I suspect that this is a issue with how the accessibility functions work, And without a touch input device, The mouse input will no longer function as expected. Also, Keyboard input works as it should.

![1](https://github.com/user-attachments/assets/bfd9547c-2b26-45d8-a0ba-b0117e5c4b03)

![2](https://github.com/user-attachments/assets/991aa13e-ab88-421a-974b-e3c78817101a)

**Comment by bk138** [comment]
Can you please describe your setup in more detail? A topology sketch or the like. It is hard to figure out what your use case is.

**Comment by damienwolf07** [comment]
> Can you please describe your setup in more detail? A topology sketch or the like. It is hard to figure out what your use case is.

Hmm what aspect do you want more detail about?

**Comment by damienwolf07** [comment]
I will just put these here just in case.
I am running this without a screen because the battery was expanding, And this phone is plugged in pretty much 24/7, I have fast-boot configured to boot android when power gets connected.
This phone will be put somewhere remote once everything gets sorted out, Which will be the reason for VNC.
This phone runs a NTP GPS server on boot and some other things when required.

![IMG_20240727_170244409](https://github.com/user-attachments/assets/133c4120-1a00-4252-b7f2-86b8d88170e6)

![IMG_20240727_232212353](https://github.com/user-attachments/assets/4ce75429-c944-4db0-92e5-0f7afab355d6)

![IMG_20240727_232205803](https://github.com/user-attachments/assets/9c028922-9ba1-491f-ba1a-c6aeb8dc67be)

**Comment by damienwolf07** [comment]
Update: ``scrcpy`` seems to work perfectly fine with my application, That is, For this mouse control issue.

**Comment by bk138** [comment]
@damienwolf07 So you have a

- moto g6 without a physical screen
- running droidVNC-NG
- when a touch digitizer (is that a touchpad without screen?) is connected, VNC mouse input does _not_ work
- when a BT mouse is connected, VNC input does work OK

Correct?

In any case, this is probably rather in the scope of AOSP, so you might want to report there.

Few things you can try nonetheless:
- try with alfavnc
- try with teamviewer

If they're affected, as well, you have an AOSP platform issue, if not, you have at least a working solution. HTH!
