### ISSUE TITLE
SSH instructions for README

### ISSUE THREAD

**Issue by ddevz** [bk138/droidVNC-NG#226]
I think it'd be good to have some ssh instructions in the README.  
Something like:

It is possible to encrypt communications through a ssh tunnel. To do that:
1. Install a ssh server on your android device.  one option is: https://f-droid.org/packages/org.galexander.sshd/
2. Configure it for port 2222
3. Start the sshd server
4. Then from the computer you intend to run the vnc client on, do:
  ssh-keygen -t ecdsa;  cp .ssh/id_ecdsa.pub ~/authorized_keys; scp ~/authorized_keys -p 2222 {ip address of android device}
   (note: if ssh-keygen says the key already exists, then do not overwrite it)
5. On the screen of the android, it will tell you a one time password, enter that in as the password
6. Once the authorized_keys file has successfully copied, from the computer you intend to run the vnc client on, do:  
    ssh -p 2222  -L localhost:5900:localhost:5900 {ip address of android device}
then:
    vncviewer localhost:5900

**Comment by ddevz** [comment]
Example instructions are actually in the issue now.  (Originally issue was accidentally created before it was fully written)

**Comment by bk138** [comment]
Thanks for the idea! I opt for not adding this as it's very common SSH tunneling info documented in lots of places, easy to find when searching. But thanks!

**Comment by ddevz** [comment]
Maybe some links then to those places?  I've done ssh tunneling before, and it took me way too long to do.  

I think telling people about a ssh server for android (searching through all the android ssh clients to find a ssh server takes time), and at least having the words "ssh tunneling" in there, and a pointer to a ssh tunneling howto (so people dont have to come up with the idea of ssh tunneling on their own) could save people some time.

But whatever you want.  I'm just trying to help.
