### ISSUE TITLE
Add security via a option to *only* listen to localhost:5900

### ISSUE THREAD

**Issue by ddevz** [bk138/droidVNC-NG#227]
**Is your feature request related to a problem? Please describe.**
The default listening action for droidVNC-NG is to listen on all interfaces (including localhost and external ip address).  (this can be seen from termux with "netstat -lnt")
Those that have secured their systems with a ssh tunnel, will use the localhost address, but having the interface still open on the external ip address makes one vulnerable when problems like : https://github.com/bk138/droidVNC-NG/issues/219 arise.

**Describe the solution you'd like**
A option to **only** listen to locahost:5900, and not listen to the external interface

**Describe alternatives you've considered**
In issue https://github.com/bk138/droidVNC-NG/issues/93 , it seems like he is saying that he got his to listen just to 127.0.0.1:5900 via UI, so its possible this is already implemented and I'm just not understanding the UI.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.5.0
 - Android version: 9

**Comment by bk138** [comment]
Thanks for reporting! This is actually a dupe of #43, please subscribe there!
