### ISSUE TITLE
Input: DENIED

### ISSUE THREAD

**Issue by AndyM48** [bk138/droidVNC-NG#229]
**Describe the bug**
After setting permissions I still see Input; DENIED
![Screenshot_20240809_122758_net christianbeier droidvnc_ng](https://github.com/user-attachments/assets/e9564561-5e63-44df-baeb-7623a3053316)

Running on Huawei Y6 2019
Android 9
EMUI 9.1.0
droidVNC-NG 2.5.0

Apps>Permissions> Storage droidVNC-NG true

**To Reproduce**
Start droidVNC-NG

**Expected Behavior**
Input: GRANTED

**Additional context**
I have seen several other bug reports her, but none seem to have a solution.

Thanks for your App and for your help

**Comment by bk138** [comment]
Thanks for your report! Please:

- try with alphavnc, see what happens and post the result here
- provide a logcat dump beginning with droidVNC-NG start and ending with the screen you're seeing above

**Comment by AndyM48** [comment]
alphavnc does not seem to work either. Can connect from client, but no input possible.

logcat for droidVNC is available [here](https://ln5.sync.com/dl/4e2b1bf50/qqvkqdqq-y346rmhm-ccmqkfp5-j8bevqid)

Thanks for any help

**Comment by bk138** [comment]
` java.lang.ClassNotFoundException: Didn't find class android.accessibilityservice.AccessibilityService$TakeScreenshotCallback" ` looks interesting. This refers to https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.TakeScreenshotCallback which was added for Android 10, so your device doesn't have it. But the code using it is not executed for Android 9. So basically, no good idea. Might be a vendor bug...

**Comment by AndyM48** [comment]
OK, thank you for looking. Indeed Huawei can be a pain. I will try searching all the less obvious settings.

**Comment by th1031** [comment]
Experiencing the same issue as @AndyM48 (OP) - droidVNC-NG is denied accessibility usage (input), while alpha vnc lite is allowed and works. Some photos attached.

![accessibility-disabled](https://github.com/user-attachments/assets/d247059b-ce92-4f02-960b-f837dbd05bec)
![restricted-setting](https://github.com/user-attachments/assets/d5a122fa-1d8e-4436-8d4e-861b8c08afe0)
![alpha_vnc_ok](https://github.com/user-attachments/assets/7500d366-7a1e-4473-a8f4-86bf47fcec34)

**Comment by bk138** [comment]
@th1031 please post:

- logcat output
- how you installed the app

Thanks!

**Comment by AndyM48** [comment]
So I may have solved my problem, but it has to be proved yet:
1. On droidVNC-NG select START
2. Go to Accessibility as prompted
3. Under INTERACTION CONTROL tap on Accessibility Shortcut

![Screenshot_1](https://github.com/user-attachments/assets/4fc588f6-29f2-48ce-9188-093a45587e67)

and select droidVNC-NG

5. Under DOWNLOADED SERVICES tap on droidVNC-NG and turn it on

![Screenshot_2](https://github.com/user-attachments/assets/4a89d7ef-af8f-40b3-91d7-aa237d971f68)

6. Accept OK

![Screenshot_3](https://github.com/user-attachments/assets/90a897ab-8a7f-4de0-9e10-d955df054dea)

Hopefully that might help someone

**Comment by th1031** [comment]
> @th1031 please post:
>     * logcat output
>     * how you installed the app
> Thanks!

Sorry - out of town a couple of days.
Installed by downloading v. 2.5.0 from F-Droid, installed from a file manager with install perms.
logcat.out.txt attached
[logcat.out.txt](https://github.com/user-attachments/files/16645362/logcat.out.txt)

**Comment by bk138** [comment]
> > @th1031 please post:
> > * logcat output
> > * how you installed the app
> > Thanks!
> 
> Sorry - out of town a couple of days. Installed by downloading v. 2.5.0 from F-Droid, installed from a file manager with install perms. logcat.out.txt attached [logcat.out.txt](https://github.com/user-attachments/files/16645362/logcat.out.txt)

You need to install from a "store" app directly, otherwise Android imposes additional security restrictions.

**Comment by bk138** [comment]
@AndyM48 If i understand correctly, you could solve your issue? I'm tentatively closing this report, let me know if it's not solved.

**Comment by AndyM48** [comment]
It was solved as detailed in my [message]( https://github.com/bk138/droidVNC-NG/issues/229#issuecomment-2289280481). The solution may help others.

**Comment by th1031** [comment]
> > > @th1031 please post:
> > > 
> > > * logcat output
> > > * how you installed the app
> > >   Thanks!
> > 
> > 
> > Sorry - out of town a couple of days. Installed by downloading v. 2.5.0 from F-Droid, installed from a file manager with install perms. logcat.out.txt attached [logcat.out.txt](https://github.com/user-attachments/files/16645362/logcat.out.txt)
> 
> You need to install from a "store" app directly, otherwise Android imposes additional security restrictions. See https://www.reddit.com/r/AndroidQuestions/comments/139tyju/i_tried_to_turn_on_accessibility_option_and_it/ and other places on the web.

Thank you! As it turns out, from my installed apps list, I simply had to open droidVNC-NG, and from the App permissions three dot menu upper right of the screen, select "Allow restricted settings". I especially appreciate that I can initiate a remote session without needing verification/permission from the remote end. Thank you for your work on this project.
