### ISSUE TITLE
Add UTF-8 clipboard support

### ISSUE THREAD

**Issue by master255** [bk138/droidVNC-NG#234]
@bk138 The application supports English language only. How to transfer (via clipboard or keyboard) another language? 
Other languages are transmitted with errors.
We need to add support for other languages.

**Comment by bk138** [comment]
re #106, re https://github.com/LibVNC/libvncserver/pull/561, re https://github.com/LibVNC/libvncserver/issues/592

**Comment by bk138** [comment]
@master255 which client are you using? This issue will be about clipboard only, let's handle keyboard in a different one.

**Comment by master255** [comment]
@bk138 I am using the built-in web novnc client from the latest version 2.6.0.

**Comment by w1s3one805** [comment]
> @bk138 The application supports English language only. How to transfer (via clipboard or keyboard) another language? 
> Other languages are transmitted with errors.
> We need to add support for other languages.

https://github.com/bk138/droidVNC-NG/issues/234

**Comment by eric-et** [comment]
> [@bk138](https://github.com/bk138) I am using the built-in web novnc client from the latest version 2.6.0. Ok

Hi, may i ask what do you mean by the built-in novnc client ok? did you test non-english languages thru clipboard?
As i can see the build-in novnc is a link to original novnc project of a specific version and they do have the clipboard encoding issue even for their latest version.

**Comment by Neustradamus** [comment]
@eric-et: Interesting :)
