### ISSUE TITLE
Can't activate Input on Android 8 Philips Smart TV

### ISSUE THREAD

**Issue by Dyriam41** [bk138/droidVNC-NG#238]
**Describe the bug**
Can't enable Input on Philips SmartTV. I get an "Accessibility Disabled" warning. Clicking "yes" to enable gets the error "Could not find the default accessibility settings activity", and there is no Accessibility settings when I try to access manually. Is there any workarounds?

**To Reproduce**
1. Click Start
2. Get the error

**Expected Behavior**
There should be a way to enable Input, right?

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.6.0
 - Android version: 8.0.0 4.9.44 
 - Client-side OS and version: Windows 10 Pro 22H2
 - VNC client and version: RealVNC (Client connects and displays remote screen, I just can't remotely control it)

![Error 1](https://github.com/user-attachments/assets/b7173dc6-d757-4fb3-ac26-c32ac8ce5b20)
![Permissions](https://github.com/user-attachments/assets/08f819bb-3446-4d21-b08f-b0d445909ee3)

**Comment by bk138** [comment]
That dialog from the first screenshot is expected on TVs. You have to somehow manually navigate to the Accessibility settings. https://tv-sound-monitors.philips.com/s/article/What-accessibility-settings-are-available-on-the-Philips-Google-TV-1702646452585?language=en_US has a hint, I think.

**Comment by bk138** [comment]
Tentatively closing, feel free to post new info here once available.

**Comment by bk138** [comment]
Hi! I'm confused. You wrote it that it's a Philips TV, isn't it?

You can disable the need for that setting by turning "start on boot" to off and "view only" to on in the droidVNC-NG Admin Screen.

**Comment by bk138** [comment]
PS: you can also check bullet point 3 in https://github.com/bk138/droidVNC-NG?tab=readme-ov-file#notes
