### ISSUE TITLE
Mouse pointer on VNC Client screen

### ISSUE THREAD

**Issue by AndyM48** [bk138/droidVNC-NG#242]
#137 suggests that I should see a mouse pointer in the VNC Client screen when I vnc into the smartphone, but I don't. I have to guess where the pointer is. If I guess right and left_click then the action is activated, but it is very hit-and-miss.

droidVNC-NG v2.7.2
Linux acer 6.11.1-artix1-1 #1 SMP PREEMPT_DYNAMIC Wed, 02 Oct 2024 15:03:06 +0000 x86_64 GNU/Linux
TigerVNC v1.14.0

I have added 'defaults.json' with "showPointers": true, included in it.

**Comment by bk138** [comment]
Thanks for your report. Please note that the defaults.json is targeted for mass-installations, you can simply enable server-side cursors in the Admin Panel.  Some screenshots and, most importantly, logcat dumps, will help diagnosing.

**Comment by bk138** [comment]
Tentatively closing, please post new info here once available.
