### ISSUE TITLE
Failing to connect with the noVNC viewer

### ISSUE THREAD

**Issue by unique-EJ** [bk138/droidVNC-NG#246]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

From the web page DevTools log:
-  `❌️ Failed to load resource` (from URL `http://`[server IP address]`:5800/core/util/int.js`) `: net`(work)`::ERR_EMPTY_RESPONSE`
- (×6) `The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate 'as' value and it is preloaded intentionally.`
- Issue (2 resources) - `A <label> isn't associated with a form field.`
  `To fix this issue, nest the <input> in the <label> or provide a for attribute on the <label> that matches a form field id.`

**To Reproduce**

Steps to reproduce:
1. I opened version 2.7.2, downloaded from Google Play Store.
2. I started the VNC server & opened the browser viewing link in Chromium on my laptop.
3. Nothing changes when the web page is transitioning to a loaded app.

**Expected Behaviour**

A loaded noVNC viewer.

**Your environment (please complete the following information):**
 - droidVNC-NG version: 2.7.3
 - Android version: 14
 - Client-side OS and version: Arch Linux (64-bit)
 - VNC client and version: default noVNC HTML5 client

**Comment by bk138** [comment]
Thanks for your report! Just tried w/ Chromium 130.0.6723.91 which works for me. Are you able to ping the Android device from your laptop and/or use native VNC?

**Comment by bk138** [comment]
Tentatively closing, please post here once there's new info available.
