### ISSUE TITLE
Screencast without having to Grant Permissions

### ISSUE THREAD

**Issue by Sepero** [bk138/droidVNC-NG#25]
Request to include information in the app on how people can permanently give permission to screencast.

adb shell cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow

Including the command, and a url link to using ADB should be enough. You've done a good job of keeping the interface clean. I trust you'll keep it that way. Thank you

**Comment by bk138** [comment]
Neat! Thanks a a lot for pointing this out! Where did you find out about this?

**Comment by Sepero** [comment]
With a lot of digging I found someone else posted it in the in the TeamViewer forums. I tried it with droidVNC, and bingo it worked first try.

Now with Termux, it's possible to

1. Run background services sshd and Tor (Tor for having a xxxx.onion address that doesn't change).
2. Connect over ssh, and remotely start droidVNC as needed.

Good for remote assistance, or remote controlling your own device if it gets lost 😊👍
