### ISSUE TITLE
UltraVNC repeater connection stuck on "negotiate protocol version"

### ISSUE THREAD

**Issue by cyberkrikk** [bk138/droidVNC-NG#250]
UltraVNC repeater is up, DroinVNC-NG can connect to it, and i can see connection in the UltraVNC repeater WebGUI, but when i tries to connect through repeater with UltraVNC viewer - it stucks on "negotiate protocol version" and nothing happens.

Details on attached screenshots.

 - droidVNC-NG version: 2.7.3 - latest available on Google Play
 - Android version: 13
 - Client-side OS and version: Windows 10
 - VNC client and version: UltraVNC viewer, 1.5.0.0 - dev

![UltraVNC stuck on negotiate](https://github.com/user-attachments/assets/51d95fa6-08be-4b09-81e8-2fd49b4e121c)
![UltraVNC](https://github.com/user-attachments/assets/377ad2fb-2379-4c7c-a168-7264ded17279)
![photo_2024-12-08_00-53-57](https://github.com/user-attachments/assets/e01bcaa3-afa9-408b-ab0d-959054c2c791)
![photo_2024-12-08_00-53-51](https://github.com/user-attachments/assets/c8d9756d-08ea-44de-b28d-7f6f5063189c)

**Comment by bk138** [comment]
Thanks for reporting! Which repeater mode are you using? Also, what's the repeater version?

**Comment by cyberkrikk** [comment]
Repeater mode 2. As you can see on attached to original request screenshot
- droid device is connected to repeater.
About repeater version- it's from the same installation file as  UltraVNC
viewer. I think it is 1.5.0.0 - dev.

вс, 8 дек. 2024 г. в 01:15, Christian Beier ***@***.***>:

**Comment by bk138** [comment]
@cyberkrikk Just tried it with uvncrep v0.17 (that's the repeater's Linux version), droidVNC-NG v2.7.3 and UltraVNCViewer v1.5.0.1.dev - works. 

Note that on the UltraVNCViewer side you really have to give the repeater ID in the form of `ID:123` (with the `ID:`).

**Comment by cyberkrikk** [comment]
Thanks, i will try 1.5.0.1

**Comment by bk138** [comment]
Tentatively closing this one, feel free to post new info here once available.
