### ISSUE TITLE
Inputs not working Google TV

### ISSUE THREAD

**Issue by pozineg** [bk138/droidVNC-NG#254]
Hi,

I can confirm the same issue user wirtualka85 reported earlier. What happens on my both Google TVs was described in Exact words. I'm opening this unresolved issue again as it has been previously closed for some reason. 

I've tried all your suggestions plus restart/reinstall but nothing works. Would you mind trying to resolve it?

Thanks

**Comment by bk138** [comment]
@pozineg I would mind, but I don't know how. I've reopened #244 for you, please report there what you tested, also a complete adb logcat dump would be very helpful.
