### ISSUE TITLE
app freezes when using domains for reverseVNC

### ISSUE THREAD

**Issue by DJCrashdummy** [bk138/droidVNC-NG#29]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

beforehand: thank you very much @bk138 for such an awesome FOSS app!!!
i've looked so long for an FOSS no root VNC server on android... and now it popped up on fdroid, and it even has reverseVNC resp. VNCi. :clap: 

**Describe the bug**
...sadly that's also where i experience kind of a bug: as soon as i try to use a domain for reverseVNC, the app seems to freeze.

**To Reproduce**
1. open droidVNC-NG
2. start server
3. grant permissions
4. tap "connect to a listening viewer"
5. enter any domain (whether with or without port) and tap "ok".
6. see the app frozen :frowning_face: 
7. sometimes after ~3 minutes the input field closes with a toast message that the connection failed.

**Expected Behavior**
reverseVNC should also work with domains, as i guess most of the time it is the point of reverseVNC to make it easier for the person with the server.
BTW: having a kind of a history or list to save reverse connections would come in handy! ...or perhaps even a widget to start a particular reverse connection (resulting in a "one-tap-support") would be absolutely brilliant!

**Your environment (please complete the following information):**
 - OS and version: android 7.1.2
 - VNC viewer and version: doesn't matter... it's the same for different viewers or even if you don't use any at all. :stuck_out_tongue_winking_eye: 

**Additional context**
using the local IPs works like charm, whether for a normal VNC connection or also reverseVNC (even if i try all 3 within the "same session").
BTW: interestingly i noticed the same behaviour (as described in the procedure) when i mistakenly used the IP of my router for a reverse connection.

**Comment by DJCrashdummy** [comment]
unfortunately no other issue i can think of...
- the service is reachable: i had the same issue with *droidVNC-NG* yesterday, but using it via a *UltraVNC SingleClick* and `x11vnc` worked flawlessly.
- ...so i can also rule out that the port is filtered.
- yes, using the IP works like a charm.

**Comment by DJCrashdummy** [comment]
interesting...! now i tried *droidVNC-NG* on an other device and the same setup worked flawlessly. :thinking:

**Comment by bk138** [comment]
> interesting...! now i tried _droidVNC-NG_ on an other device and the same setup worked flawlessly. thinking

It might be worth attaching adb and getting the output of `adb logcat`.
