### ISSUE TITLE
Cannot unlock lock screen on Xiaomi

### ISSUE THREAD

**Issue by apmcgh** [bk138/droidVNC-NG#37]
**Describe the bug**
There seem to be no way to unlock the screen using the VNC session on a Xiaomi Redmi Note 9, Android 11.
The computer Home key works to unlock the screen on a Samsung Galaxy A72, but not on the Xiaomi.

A possible cause of this behaviour is that the Xiaomi does not have a home key.
To unlock the screen on the phone, one must use the power button.

**To Reproduce**
Start DroidVNC / Enable accessibility & shortcuts
Start session
Lock screen
Start vncviewer on computer
Press home key (or any other for that matter, including ctrl-shift-esc), the screen stays locked.

**Expected Behavior**
Some key combination allows to unlock the screen on a Xiaomi Redmi Note 9.

**Logs/Backtraces**
n/a

**Your environment (please complete the following information):**
 Phone: Android 11 / DroidNG 1.2.3
Desktop: Ubuntu 18.04, vncviewer: TigerVNC Viewer 64-bit v1.7.0

**Additional context**
A secondary problem occurs:
After I press the power key to light up the screen, still locked, I seem to be able to "swipe up", the phone screen shows the on screen keyboard, but the vncviewer window is still blank (black). Some key combination (not sure which, it does not seem consistent) allowed me to light up the vncviewer window and see the on screen keyboard, but it blanked on the phone and I was not able to interact with it.
When unlocked, I can interact with the phone.

**Comment by Martii** [comment]
These might be relevant in greater than Android 9

Refs:
* https://security.googleblog.com/2020/09/lockscreen-and-authentication.html
* https://source.android.com/security/biometric/measure

Some of this is "Greek" to me however I do know that `adb` can simulate button presses via `scrcpy`. As I mentioned elsewhere that has stiffer requirements *(USB/WiFi debugging on)* and caveats *(reconnect once with USB if out of WiFi range)* that makes using it cumbersome which is why I would prefer to utilize this cool project instead.

**Comment by CongAn** [comment]
我使用聊天通讯软件的语音呼叫来点亮屏幕，解决了黑屏解锁问题。
我在中国，使用的QQ通讯软件，这段话是翻译的，你可能看不懂。

I use the voice call of chat communication software to light up the screen and solve the problem of black screen unlocking.
I use QQ communication software in China. This paragraph is translated. You may not understand it.

**Comment by olivluca** [comment]
I have the same issue with a moto e 4g (2015, surnia) running lineageos 17.1 (android 10).

**Comment by LuisMiguelAlmeida** [comment]
@bk138

I have a moto e7 plus where if I click on ESC I can wake him up which is already nice for me,
I also have a Samsung   TAB Active Pro 10 that I can not wake him up from a vnc viewer, is there any way I can send the home button key event to waking him up?

**Comment by bk138** [comment]
@LuisMiguelAlmeida Home is mapped to Home ;-)

**Comment by LuisMiguelAlmeida** [comment]
@bk138 sorry I didn't understand. I am using a vnc viewer in Windows and I would like to use the on/off button, home button, back button and the other physical buttons...

If you are referring the Windows button as the home button then it doesn't work.

If you could help me I will apreciate :)

**Comment by bk138** [comment]
@LuisMiguelAlmeida you were asking on how to "send the home button key event": when you press the "Home" key on PC connected via VNC viewer to the droidVNC-NG server, it triggers a virtual home button press on the Android side.

**Comment by olivluca** [comment]
Pressing the home button here does nothing (i.e, it's not enough to turn on the screen).
What's worse, if try to send a notification to the phone (e.g. by using "find my device") I still see a black screen on the vnc client.
I can also connect via ssh, maybe is there a command to turn on the screen?
I tried
```
input keyevent KEYCODE_POWER
input keyevent KEYCODE_WAKEUP
input keyevent 224
input keyevent 26

```

as suggested [here](https://stackoverflow.com/questions/7585105/turn-on-screen-on-device) but none of them worked.

**Comment by bk138** [comment]
@LuisMiguelAlmeida I think not, but your possible  research might find out otherwise.

**Comment by olivluca** [comment]
It turns out that 

`input keyevent KEYCODE_POWER`

as root actually works to turn on the screen on my moto e.
Before discovering that the problem was a setting in the vnc client (d'oh!) I  tried the following, convoluted, method, that also works.
First of all, I have root (magisk) and an ssh server on the phone. I connected via ssh , issued a "getevent" command, then I pressed and released the power button on the moto e.
This gave me these codes:

```
/dev/input/event4 1 74 1
/dev/input/event4 0 0 0
/dev/input/event4 1 74 0
/dev/input/event4 0 0 0
```
So I tried to replicate that with these commands (74 is in hex, sendevent needs decimal)

```
sendevent /dev/input/event4 1 116 1
sendevent /dev/input/event4 0 0 0
sendevent /dev/input/event4 1 116 0
sendevent /dev/input/event4 0 0 0
```
And it also turns on the screen.

**Comment by bk138** [comment]
Hey guys, please test with [this APK](https://we.tl/t-9WitLmmVq8), it contains the the changes above that should wake up the device once a client connects. The screen stays on only for a few seconds though on my test device, but it's enough in most cases to enter the lock screen secret. Please be so kind and report how it works for you.

**Comment by Android-X13** [comment]
Hi @bk138, I just tested the apk and here's what happens on my (Huawei) phone:

If the phone's screen is off when I try to connect, it now lights up and I can see the contents in the VNC viewer. However I have to swipe up to unlock the phone, and when I do the VNC viewer's window turns black. Disconnecting and reconnecting doesn't help as the viewer remains black upon any further reconnections. Only if I manually turn the phone screen's off and then try to reconnect I will be able to see the contents in the viewer's window again (phone screen wakes up but when I swipe up the viewer will turn black again, etc). So I am still unable to unlock the phone.

RealVNC viewer
Huawei Honor 10

**Comment by bk138** [comment]
> Hi @bk138, I just tested the apk and here's what happens on my (Huawei) phone:
> 
> If the phone's screen is off when I try to connect, it now lights up and I can see the contents in the VNC viewer. However I have to swipe up to unlock the phone, and when I do the VNC viewer's window turns black. Disconnecting and reconnecting doesn't help as the viewer remains black upon any further reconnections. Only if I manually turn the phone screen off and then try to reconnect I will be able to see the contents in the viewer's window again (phone screen wakes up but when I swipe up the viewer will turn black again, etc). So I am still unable to unlock the phone.
> 
> RealVNC viewer Huawei Honor 10

That very much sounds like the screen for entering the secret is prevented from being recorded. Nothing we can do in that particular case. Your only option is to disable it.

**Comment by Android-X13** [comment]
The good thing is that now the screen remains on while connected (IIRC this wasn't the case before this apk) so I don't have to unlock the phone every now and then

**Comment by ZeaKyX** [comment]
> Hey guys, please test with [this APK](https://we.tl/t-9WitLmmVq8), it contains the the changes above that should wake up the device once a client connects. The screen stays on only for a few seconds though on my test device, but it's enough in most cases to enter the lock screen secret. Please be so kind and report how it works for you.

I just tested it with my phone with Android 10.0 ( MoKee ROM ) and it works like a charm!

1. When the VNC client is connected, my phone does wake up. Then after about ten seconds , the screen will dim, but the VNC client screen is normal and can be displayed and operated. I guess at this point the screen needs to be set for a timeout before the screen actually turns off.
2. This apk is not compatible with v1.2.6 release, i need to uninstall the original one and reinstall it.

**Comment by bk138** [comment]
Alright, closing this then.

**Comment by Martii** [comment]
@bk138 

Sorry for the lateness... real life has been keeping me extremely busy... but I seem to be stuck with version 1.2.3 even on the play store reinstall. Any suggestions *(releases page here on GH to sideload it?)* or am I just being impatient? :smile_cat:

**Comment by olivluca** [comment]
I guess that the app autoupdated from the play store (I'm connecting to the phone remotely so I cannot check), but now not even my workaround ("input keyevent KEYCODE_POWER") turns on the screen.
All I get I a black screen, no way to turn it on (tested with krdc on linux and avnc on android).

**Comment by bk138** [comment]
There were no changes around "input keyevent KEYCODE_POWER" in the app.

**Comment by olivluca** [comment]
I guessed so, still, the screen doesn't turn on. What key combination should the vnc client send to turn on the screen?

**Comment by olivluca** [comment]
(the screen as seen by the vnc client, I cannot check with the phone right now)

**Comment by bk138** [comment]
> I guessed so, still, the screen doesn't turn on. What key combination should the vnc client send to turn on the screen?

None, actually a https://developer.android.com/reference/android/os/PowerManager.WakeLock is acquired when a client logs in. It should keep the screen on (older Androids) or light up the screen for a short while at least (newer Androids w/ Doze mode).

**Comment by olivluca** [comment]
I just installed it on another phone (xiaomi redmi note 4), also on lineageos 17.1 and it has no problem waking up the screen when I connect. Maybe now it needs a new permission (that I cannot grant until I phisically access the phone)?

**Comment by bk138** [comment]
> I just installed it on another phone (xiaomi redmi note 4), also on lineageos 17.1 and it has no problem waking up the screen when I connect. Maybe now it needs a new permission (that I cannot grant until I phisically access the phone)?

It has to do with this thing called "Doze Mode", see https://stackoverflow.com/questions/32286797/wakelock-and-doze-mode for instance. IIRC you can manually exempt an app from it via Settings or so...

**Comment by olivluca** [comment]
Well, I'll have to wait until I can phisically access the phone (unless I find a way to do something with the command line).
