### ISSUE TITLE
Inputs not working after some time

### ISSUE THREAD

**Issue by gigovx** [bk138/droidVNC-NG#38]
**Describe the bug**
No input from remote device on server device

**To Reproduce**
Keep an active connection, after time the server device fails to respond to inputs, but not on all devices I am operating

**Expected Behavior**
Inputs to be sent to device

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - OS and version:  Windows 11 264 & Android 11
 - VNC viewer and version: Real VNC Viewer 6.21 (and TightVNC)

**Additional context**
I have tried different VNC viewers and the same response
I have disconnected and re-connected and it does not resolve the issue
I have used different devices to connect, (both Android and Windows)
Only restarting the server device manually (ie physically in person) seems to solve the issue
I can still awake the screen on by pressing ctrl+esc but no other inputs are being sent once screen is awake other than esc

**Comment by bk138** [comment]
Thanks for reporting! How would one be able to consistently reproduce this? Could you maybe try with an emulator and then share its version and setup?

**Comment by bk138** [comment]
Thanks a lot, Giles! I fear - however - that I won't be able to repro this without a device where it's happening.

**Comment by gigovx** [comment]
I figured as much, is there a way to get a log file to you so you can see what the issue maybe?

Warmest Regards
Giles
________________________________

**Comment by bk138** [comment]
The usual logcat way and a lot of patience I guess ;-): https://support.citrix.com/article/CTX232375

**Comment by peekd** [comment]
Hi @bk138, thanks for fixing this.  How can I download an apk with this fix in it or will I need to wait for a new version to be released?  If so, when might that be?
Thanks again!

**Comment by bk138** [comment]
Here you go: https://github.com/bk138/droidVNC-NG/releases/tag/v1.2.4 

NB that this release will not be available on Google Play due to #52

**Comment by Jdogzz** [comment]
@bk138 Thanks for packaging that as an apk (it was on my todo list to figure out how to build Android apps from source). Unfortunately I see the same problem as before, within a couple of minutes I see a broken connection and then all reconnects do not respond to gestures. I can't tell if it's related to gesture length, though. In a couple of tests just now, a few simple taps over a few minutes put it into that state, while in a followup test after restarting the emulator I was getting continuous gestures lasting over 30 seconds after a single tap, then a deliberate continuous click and drag showed no response on Android's end, and after all that VNC continued to work correctly.

**Comment by bk138** [comment]
@Jdogzz As I pointed out in https://github.com/bk138/droidVNC-NG/issues/38#issuecomment-950388952, I was able to reproduce the input lockup by doing a gesture that lasts over 60s. I applied #48 and this was fixed for me.

If there's still an issue on your side, please post a way to (hopefully quickly) reproduce together with some logcat output. Tip: you can write into the logcat text file what action you took after sampling it, that makes things easier to understand.

**Comment by peekd** [comment]
Hi @bk138, Just letting you know that the last update has fixed my issue with the android app not receiving inputs after some time.  It has been running for over 3 days now without issue.  Previously it would have definitely failed - a few times!  Thanks for the fix!
