### ISSUE TITLE
Zoom gesture support

### ISSUE THREAD

**Issue by gitgrub** [bk138/droidVNC-NG#39]
First let me thank you for this tool, works really good.
Using VNC for my PCs since ages, I am happy that this works rootless on android, too. There are other VNC servers on g-play, but rather spooky tools, I dont like them.
I am impressed by the speed of your droidVNC, using the camera on the remote device, the lag to the PC is really minimal.
The missing keyboard support is no big deal for me, as I just use it to support my mother on her tablet from remote.

Now my request is:
I would like to use the zoom gesture in an app on the remote device. The two finger thing.
I dont know if this is easy to implement, I would expect holding the secondary mouse button and use the mouse wheel to zoom in and out. Idk if there is a more elegant way to do that from a PC.

**Comment by bk138** [comment]
Thanks for your feature idea! I think this is rather something for the client side - which client are you using? (There are a bunch of them out there with client-side scaling...)

**Comment by gitgrub** [comment]
Its about opera browser. The zoom feature in a web page works very good for bad eyed ppl, as opera does line breaks so that you see the whole content on the screen, versa chrome that just zooms in and the user has to scroll horizontally all the time. Now when zoomed in like crazy, its hard to find the right spot on the page to do something, I would like to zoom out a bit to see where I need to click/enter text, etc. I think thats the two finger action on the android system.

There seems not to be an "reset zoom to 100%" option on opera for android, yep thats a client thing.
On the other hand, the two finger option is a normal action for android devices, question is how this could be emulated by VNC/PC. Idk whats sent to the touch system when using two fingers.

Hm, I found that, but thats the other way around, the receiving part, dont know if that helps:
https://developer.android.com/training/gestures/scale

**Comment by bk138** [comment]
In case you're using a Android viewer, there is my other project [MultiVNC](https://github.com/bk138/multivnc) which supports pinch-to-zoom.

**Comment by gitgrub** [comment]
I am using last version tightVNC on win10.
I found your droidVNC, was impressed by its speed, looked at you projects and unzipped MultiVNC to take a look. Works on win PCs, but connecting to an android device crashes it, the program disappears.

What I see: when the screen saver ist active/black on the android device, I can connect to it.
When the screen goes active, multivnc crashes.
When connecting to an active screen on the tablet, multivnc crashes.

Device is a samsung galaxy tab s5e, android v11.
Is there a command line switch for multivnc to write to a log file?

**Comment by gitgrub** [comment]
Ah, now I see you are talking about the android version of multivnc. I am comfortable of using the PC for remote control, need to think about using a tablet, smaller screen and such :)

**Comment by gitgrub** [comment]
Yes thank you, zooming works good from tablet to tablet, merci.
Problem solved for me.
