### ISSUE TITLE
Wiki or FAQ: how to wake up from screensaver?

### ISSUE THREAD

**Issue by inspector71** [bk138/droidVNC-NG#42]
Great app. Thank you for producing the 1st ever open source remote access app that seems to be easy to install and has substantial potential.

Could I contribute to a Wiki or documentation effort to add some documentation for the basics, at least?

On first run, was not immediately obvious to me that `Esc` (back?) would wake up the screensaver ... without sending through an unwanted keypress whilst doing so :)

Maybe a Wiki and / or FAQ page may help?

**Comment by bk138** [comment]
dupe of #37, let's tackle the challenge there

**Comment by sudomain** [comment]
My method for waking the device (software ESC didn't work for me) is to ssh into the device and send a notification. I keep Termux's `sshd` running and use Termux:API's `termux-notification` to wake it. Thought I'd just post it here incase a wiki page is made.
