### ISSUE TITLE
File transfer not working on Android >= 9

### ISSUE THREAD

**Issue by elchako** [bk138/droidVNC-NG#47]
Thank you very much for the working VNC for Android.
Tell me how to transfer files to the device?
The file system is not visible on Android 9
I am using TightVNC viewer for Windows version 1.3.10

![2021-10-21_19-54](https://user-images.githubusercontent.com/82187221/138416043-e8a83de3-c5e7-451b-bded-e42be90f227a.png)

**Comment by bk138** [comment]
Closing for now, feel free to re-open or post some info once there is some.

**Comment by bk138** [comment]
Alright, this seems to be a security tightening on newer Android versions, I get `2021-11-14 23:23:58.646 512-512/? E/audit: type=1400 audit(1636928638.641:63799): avc:  denied  { read } for  pid=18399 comm="Thread-101" name="/" dev="dm-0" ino=2 scontext=u:r:untrusted_app_29:s0:c221,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 SEPF_SM-G970F_11_0010 audit_filtered` on Android 11.
