### ISSUE TITLE
[Feature] "View only" mode

### ISSUE THREAD

**Issue by CocoCocoAlx** [bk138/droidVNC-NG#50]
Hi, I would like to know if there is any way I can use the program in "view only" mode, without using the accessibility permissions, as in Android 9 Go they are usually disabled and do not allow me to run the server at startup. Really I like much this app, I want to remotely control a bunch of Android tablets from a PC, but with this problem it gets very complicated.

**Comment by bk138** [comment]
Hi! You simply don't give the input permission when asked for. Does this solve your issue?

**Comment by CocoCocoAlx** [comment]
Yes, I just found out that it works anyway, but the sign that shows up is kind of intimidating. I'll see if there's a way I can hide it. Thanks for your work!

**Comment by bk138** [comment]
Hi, which sign?

**Comment by CocoCocoAlx** [comment]
I refer to this warning. I would like to be able to hide it, as I do not need to activate it.

![Screenshot_20211103-074153_1](https://user-images.githubusercontent.com/17306026/140046845-b815d47e-37a4-46a3-ac5a-c26ab126fe6f.png)

**Comment by bk138** [comment]
alright, that could be a config

**Comment by bk138** [comment]
@bradaker yeah, that issue here is for having a setting: "no remote control" or "view-only-mode" so that the server never needs to ask the user for permission.

**Comment by bradaker** [comment]
Great, thanks!
