### ISSUE TITLE
Accessibility using ADB

### ISSUE THREAD

**Issue by Droidphilev** [bk138/droidVNC-NG#53]
Hi,
Thanks for this app! I would like to use the server on a wierd device: a "network radio" which is a walkie talkie but Android OS on it. Accessibility service is stil in the device but left out of settings. I can only enable the service for apps using an ADB command. Would you mind letting me know the ADB command to enable Accessibilty service for DroidVNC-NG please?

Many thanks,
Phil

**Comment by bk138** [comment]
Uh, no idea. Does https://github.com/bk138/droidVNC-NG#notes help?

**Comment by Droidphilev** [comment]
Hi again,
Thanks for your answer. Sadly this is another command. Later today i will give an example of an adb command to enable accessibilty for "Button Mapper" via ADB. Maybe it will be more clear then?

grts,
Phil

**Comment by Droidphilev** [comment]
Hi again,

Here with an example.
To enable accessibility service for "Button Mapper" i use in ADB:
"adb shell pm grant flar2.homebutton android.permission.WRITE_SECURE_SETTINGS"
"adb shell settings put secure enabled_accessibility_services flar2.homebutton/flar2.homebutton.a.ai"

to get Button Mapper out of Doze (battery optimisation i use:
"adb shell dumpsys deviceidle whitelist +flar2.homebutton"


Hope this is a bit more clear of what i mean.

grts,
Phil

**Comment by bk138** [comment]
Maybe `adb shell pm grant  net.christianbeier.droidvnc_ng  android.permission.WRITE_SECURE_SETTINGS` and `adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/ InputService` ? But am just wildly guessing - you probably have to play around with some combinations I guess.

**Comment by Droidphilev** [comment]
Thank you!!!!!

Will give it a try next time i'm able to connect the devide to pc.

**Comment by bk138** [comment]
@Droidphilev could you try this out? If so, what were the results?

**Comment by Droidphilev** [comment]
> @Droidphilev could you try this out? If so, what were the results?

Sure i will! Still my device is still used by some one else. As soon as it is back home i will try this and report back.

**Comment by Droidphilev** [comment]
Hrm, i closed this topic by accident, i'm very sorry :(

**Comment by Droidphilev** [comment]
Hello again, tried both commands:

The first one gives as error: "Operation not allowed: java.lang.SecurityException: Package net.christianbeier.d
roidvnc_ng has not requested permission android.permission.WRITE_SECURE_SETTINGS"

The second one gives as error: "Too many arguments
usage:  settings [--user <USER_ID> | current] get namespace key
        settings [--user <USER_ID> | current] put namespace key value
        settings [--user <USER_ID> | current] delete namespace key
        settings [--user <USER_ID> | current] list namespace

'namespace' is one of {system, secure, global}, case-insensitive
If '--user <USER_ID> | current' is not given, the operations are performed on th
e system user."


Any idea please?

**Comment by bk138** [comment]
Just tried a single `adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService` and that worked for me.

**Comment by Droidphilev** [comment]
Ah, a dot before 'Inputservice' :-)

Will try again next time it's with me and report back, thank you!
