### ISSUE TITLE
Not working in Samsung m30s

### ISSUE THREAD

**Issue by ShivaShirsath** [bk138/droidVNC-NG#55]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

App not working 

**To Reproduce**

**Expected Behavior**

Show the localhost:5901 VNC server

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - OS and version: Ubuntu 21.04 (hirsute)
 - VNC viewer and version: tightvncserver or tigervncserver

**Additional context**

**Comment by bk138** [comment]
Hi! Can you provide a step-by-step guide on how to reproduce the error?

**Comment by ShivaShirsath** [comment]
Open app
Set permissions
Enable accessibility
Start recording dialog poped up
When clicked on start in dialog then popup closed & reopened.
![Screenshot_20211122-174029_One UI Home](https://user-images.githubusercontent.com/59221352/142859859-bad31cb8-a9a8-4a20-8ccc-6173168c0f01.png)

**Comment by bk138** [comment]
Hi @ShivaShirsath, does the test with the ScreenRecorder app described in https://github.com/bk138/droidVNC-NG#notes work for you?

**Comment by bk138** [comment]
Tentatively closing as there's been no feedback yet, feel free to post some if there is.
