### ISSUE TITLE
Xiaomi mi a2 lite + Android 10 - black client screen

### ISSUE THREAD

**Issue by rescalda** [bk138/droidVNC-NG#57]
Installed, given all permissions:
![Screenshot_20211229-111317](https://user-images.githubusercontent.com/38831927/147652205-09fbc714-2a92-4723-998d-8a973fccd86d.png)
The client (RealVnc on Fedora 33) discovers the server and connects but shows just a black, empty screen:
![Screenshot_2021-12-29_05-24-08](https://user-images.githubusercontent.com/38831927/147652474-70e08534-4f8a-418e-b186-ff40802b40d3.png)
On the phone, I have a permanent notification stating "Doing some work"

**Comment by bk138** [comment]
Please try with https://gitlab.com/vijai/screenrecorder to see if the actual screen recording API works on your device.

**Comment by bk138** [comment]
Tentatively closing as there's been no feedback yet, feel free to post some if there is.

**Comment by MysticNynja** [comment]
I have the same issue.  I have droidVNC-NG installed on Android x86 latest version on a hyper-v vm.  The VNC server runs fine and I can connect to it but black screen.  I tried the screen recorder and that works.  Is there anything else I can try?  I am running the hyper-v manager on a Windows 11 laptop and on Windows Server 2016 with the same results.

**Comment by bk138** [comment]
@MysticNynja you're probably rather seeing #35 - can you please have a look there?

**Comment by MysticNynja** [comment]
Alright I'll try another solution. thanjs

**Comment by bk138** [comment]
> Alright I'll try another solution. thanjs

If you find some approach that works, please let us know in #35 @MysticNynja
