### ISSUE TITLE
Enable WebSockets support

### ISSUE THREAD

**Issue by bk138** [bk138/droidVNC-NG#6]

**Comment by Yonle** [comment]
There's a project called [noVNC](https://github.com/noVNC/noVNC). You can try it.

**Comment by bk138** [comment]
> There's a project called [noVNC](https://github.com/noVNC/noVNC). You can try it.

I know it and worked with it. It's a client. I was htinking about LibVNCServer here.

**Comment by Yonle** [comment]
For Alternative way, Convert TCP into WS, Because noVNC Websockify is doing that.

**Comment by bk138** [comment]
LibVNCServer has native WebSockets support, so this issue here should be easy to tackle.

**Comment by Yonle** [comment]
Ah yes! You're right!

**Comment by wozuo** [comment]
Hi @bk138 any progress on this? I'm trying to implement the websockets support using `LibVNCServer` but the HTTP connections are not reaching the HTTP server somehow... (the VNC server over TCP works though)
So what I've tried so far is copying the contents of the webclients dir from the assets folder to external storage `/storage/emulated/0/webclients` on startup of the app (just for testing). And in `droidvnc-ng.c` I'm setting:
```
theScreen->alwaysShared = TRUE;
theScreen->httpDir = "/storage/emulated/0/webclients";
theScreen->httpEnableProxyConnect = TRUE;
theScreen->httpPort = 8080;
theScreen->http6Port = 8080;
```
and after `rbInitServer(theScreen)` I'm checking the sockets:
```
if(theScreen->httpListenSock == RFB_INVALID_SOCKET || theScreen->httpListen6Sock == RFB_INVALID_SOCKET) {
        __android_log_print(ANDROID_LOG_ERROR, TAG, "vncStartServer: httpListenSock failed starting (%s)", strerror(errno));
        Java_net_christianbeier_droidvnc_1ng_MainService_vncStopServer(env, thiz);
        return JNI_FALSE;
    }
```
The console prints:
```
 Listening for HTTP connections on TCP port 8080
      URL http://localhost:8080
    Listening for HTTP connections on TCP6 port 8080
      URL http://localhost:8080
    vncStartServer: successfully started
```
as if everything is running fine, but if I try to connect to http://ipofmyphone:8080 via the browser the requests seem to not even reach the app (no log output, etc. it just loads forever). Any ideas?

**Comment by bk138** [comment]
I can at for the time being only point you at https://github.com/LibVNC/libvncserver#using-websockets for a working WebSockets example, I won't be able to spend time on this here issue in the upcoming weeks.

**Comment by wozuo** [comment]
@bk138 thanks for the quick reply, yea I implemented it using the example described in the LibVNCServer readme. No worries I'll let you know if I find something to get it to work!

**Comment by Scisaga** [comment]
try to connect http://ipofmyphone:5900/ with novnc, 5900 is default vnc port. 
i guess libvncserver implements some port multiplexing mechanism
