### ISSUE TITLE
Nvidia shield

### ISSUE THREAD

**Issue by iLLiac4** [bk138/droidVNC-NG#60]
Hi. I have tried today this vnc server on Nvidia shield and it shows the screen. Buttons home and esc works and also mouse.
However it is not possible to control it using directional keys (up, down, left, right)

Some notes:
I did further testing and after two reboots and enabled it under accessibility it starts automatically. Also mouse started to work, home, esc so it works ok even to control Kodi remotely.
I saw that vnc clients differently handle the controls. I have tried TightVNC (i like it most ATM), UltraVNC also works but I like TightVNC handling more.
It is very usable on Nvidia shield. I miss ATM only directional keys.

TNX

**Comment by bk138** [comment]
Yeah, no other keys than "Home", "Esc aka Back" and "Recent Apps" work (at the moment). Please subscribe to #4 for the tracking issue.
