### ISSUE TITLE
This app cannot run on VMware Workstation pro

### ISSUE THREAD

**Issue by xiehuajieaa** [bk138/droidVNC-NG#61]
I install Android 7 and Android 8 on the virtual machine. Neither of them can run your application, which will lead to direct flash back

**Comment by bk138** [comment]
Thanks for reporting! Please check with the ScreenRecorder app mentioned in https://github.com/bk138/droidVNC-NG#notes - if it also does not work, it hints at lacking API support.

**Comment by xiehuajieaa** [comment]
> 

I hope he can be compatible with VMware and Android x86

**Comment by bk138** [comment]
Does the ScreenRecorder work in your setup @xiehuajieaa ?

**Comment by bk138** [comment]
Tentatively closing, feel free to post new info here and I will re-open.
