### ISSUE TITLE
Can u make i can use my pc keyboard on vnc i have to use mobile keyboard by mouse.

### ISSUE THREAD

**Issue by Techlord210** [bk138/droidVNC-NG#65]
If you'd like to put out an incentive for implementing this feature, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Comment by bk138** [comment]
Thanks for your report! In the future, please scan the issue list to check if someone reported your issue before. In fact, this one here is a duplicate of #4, please subscribe there to get updates :-)

**Comment by Techlord210** [comment]
> Thanks for your report! In the future, please scan the issue list to check if someone reported your issue before. In fact, this one here is a duplicate of #4, please subscribe there to get updates :-) 

Ok sorry for dupe i searched for it that its not dupe i didn't found so i asked

**Comment by bk138** [comment]
> > Thanks for your report! In the future, please scan the issue list to check if someone reported your issue before. In fact, this one here is a duplicate of #4, please subscribe there to get updates :-)
> 
> Ok sorry for dupe i searched for it that its not dupe i didn't found so i asked

No prob, that's what I'm here for ;-)
