### ISSUE TITLE
RemoteHostkeyboard issue

### ISSUE THREAD

**Issue by alimurtazo** [bk138/droidVNC-NG#7]
The issue is visible password for user when I control an android device by using VNC, Password typing must be hidden, like when you type a password user must see only dots. please advise me how to solve this issue.

**Comment by bk138** [comment]
Can you share a screenshot please? You know a picture and 1000 words and so on.

**Comment by alimurtazo** [comment]
![image](https://user-images.githubusercontent.com/4023779/105163070-3d040500-5b35-11eb-8b1e-131a94adfb2a.png)
When administrator enters his own password, the user can see it.

**Comment by bk138** [comment]
That is something that needs to get changed in the program where the password is entered.

**Comment by alimurtazo** [comment]
i want to enter password by remote pc keyboard not by android device keyboard.

**Comment by bk138** [comment]
> i want to enter password by remote pc keyboard not by android device keyboard.

This is tracked in #4. There is currently no free time and no funding for this, so it might take a while to get implemented.
