### ISSUE TITLE
Run reverse connection on reboot

### ISSUE THREAD

**Issue by monat78** [bk138/droidVNC-NG#71]
Hi,, if is possible run droidvnc-ng on boot in command mode to make a reverse connection???

Thanks, good project.

**Comment by bk138** [comment]
Can now be done via automation apps like [MacroDroid](https://www.macrodroid.com/), [Automate](https://llamalab.com/automate/) or [Tasker](https://tasker.joaoapps.com/), see https://github.com/bk138/droidVNC-NG#remote-control-via-the-intent-interface
