### ISSUE TITLE
Input on A95X F3 Air II - not working

### ISSUE THREAD

**Issue by duiveldoder** [bk138/droidVNC-NG#74]
So it basically runs out of the box - giving the permissions manually..

when I start the app everything is showing "granted" in big fat green letters.

but then from my windows PC using tiny-VNC I can connect without a hassle - but I can't input anything usuable really..

mouse not working
keyboard 99% not working, although the "esc" key seems to be working..

any ideas?

**Comment by bk138** [comment]
Please try with another viewer and note the readme about keyboard input.

**Comment by bk138** [comment]
Tentatively closing this, feel free to post more info once you have it.
