### ISSUE TITLE
droidVNC lets revoke accessibility options of some apps

### ISSUE THREAD

**Issue by freebrowser1** [bk138/droidVNC-NG#79]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

When permissions are set permanently as described in the Github page

```` 
sudo  cmd appops set net.christianbeier.droidvnc_ng PROJECT_MEDIA allow
sudo  settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService
````
(I replaced `adb shell` by `sudo` to run it from a root shell).

Examples of the affected apps are Rotation (com.pranavpandey.rotation) and sometimes Taskbar (com.farmerbb.taskbar).

some accessibility permissions of other apps are revoked. I reproduced it on droidVNC version 1.2.3 and 1.2.6 on Oneplus 6 with Android 10 and on an Android 12 emulator of Android Studio.

**To Reproduce**
1. Install one of the abovementioned apps.
2. Grant 'Accessibility' to it.
3. Run the two scripts with `adb shell` instead of sudo with a USB connection (if not rooted) or these commands straight in a root shell terminal.
4. Run droidVNC and grant lacking permissions.
5. Now VNC server does work, but accessibility permissions of other apps are gone.

**Expected Behavior**
droidVNC should not affect permissions of other apps.

**Your environment (please complete the following information):**
 - OS and version: Android 10 and 12
 - VNC viewer and version: N/A (but RealVNC just works and shows the device screen)

**Comment by bk138** [comment]
Interesting. Does the issue show the other way around as well, i.e. if you do allow access to com.pranavpandey.rotation? 

Also, is this about `PROJECT_MEDIA allow` or `enabled_accessibility_services` or both?

**Comment by freebrowser1** [comment]
It is the 'inputService' command. I tried it the other way around as well.

`sudo  settings put secure enabled_accessibility_services com.pranavpandey.rotation/.InputService`

also revokes Accessibility to other apps, including droidVNC.

**Comment by bk138** [comment]
It's a list. I've updated the README accordingly.
