### ISSUE TITLE
Does not show host IP on Chrome OS host

### ISSUE THREAD

**Issue by CoolGames** [bk138/droidVNC-NG#81]
**Feature request related to a problem.**
When run on Chrome OS Android tablet or Chromebook the server address is not the Chrome OS address 

**Describe the solution I'd like**
Using either SSH tunnel or direct IP address access from Ubuntu Remmina , make connection to control screen
with Ubuntu keyboard and mouse.

**Ubuntu Remmina Screen with SSH port forward to external port 2022 on Penguin71cb Chrome OS host**

![Screenshot from 2022-05-11 11-59-18](https://user-images.githubusercontent.com/149711/167895149-32c5f98d-9a1f-474d-bdd8-adb8b59c37b4.png)

**Describe alternatives I've considered**
No alternative was easily found.

**Additional context**
**ASUS CM3000 Tablet Screen**

![Screenshot 2022-05-11 11 46 42 AM](https://user-images.githubusercontent.com/149711/167893320-a99306b0-b1cc-4922-a103-1a9dfe15ab5e.png)

**Comment by bk138** [comment]
* Did you start the server after you brought up the WiFi/LAN? 
* Did you try to scroll down?
* https://github.com/bk138/droidVNC-NG/blob/master/app/src/main/java/net/christianbeier/droidvnc_ng/MainService.java#L506 is how we get interfaces - might this be different on the Chromebook?

**Comment by bk138** [comment]
Maybe https://stackoverflow.com/questions/65689803/is-there-any-way-to-get-the-real-ip-of-a-chromebook-from-an-android-app is the cause?
