### ISSUE TITLE
Clipboard not working from server to client

### ISSUE THREAD

**Issue by freebrowser1** [bk138/droidVNC-NG#82]
Using droidVNC on Android 10 (oneplus 6) works ok, but pasting clipboard from device to VNC viewer does not work. The other way around (i.e. VNC client to device) does work. Clipping does work on the device itself. 
I tried both 1.2.3 and 1.2.6.
On an Android 12 emulator it does work both ways, under 1.2.3 and 1.2.6.
I use RealVNC VNC connect and the macOS builtin 'Screen sharing' VNC client. None of both receive clippings from the device. When both are connected to other VNC servers, receiving clippings do work.

Moreover, file transfer (version 1.2.3, as 1.2.6 is stuck with it) does not work neither as RealVNC tells 'file transfer not supported'.

**Comment by bk138** [comment]
Please see the third bullet point at https://github.com/bk138/droidVNC-NG/blob/master/README.md#features 

WRT file transfer, please see the seventh bullet point in there: Only TightVNC-1.3-style file transfer is supported at the moment.

**Comment by freebrowser1** [comment]
> Handling of client-to-server text copy & paste. Note that server-to-client copy & paste does not work in a generic way due to [Android security restrictions](https://developer.android.com/about/versions/10/privacy/changes#clipboard-data).

But on droidVNC on Android 12 server to client does work and using 'scrcpy' (which is not VNC but proprietary software) also copy /pastes both ways. If it were security, Android would also block copy/paste over this app.
