### ISSUE TITLE
Ability to create a VNC session under the control of another application

### ISSUE THREAD

**Issue by anreis75** [bk138/droidVNC-NG#83]
Hi Christian,
in our application we need the possibility to start a VNC repeater connection with DroidVNC-NG. I would like to create a pull request with my solution.

Kind regards
Andre

**Comment by bk138** [comment]
Just go ahead! I suggest you do it via intents, en passant you can take care of #71 and #40, i.e. just expose functionality via intents and let external automation software do the rest.

**Comment by bk138** [comment]
See https://github.com/bk138/droidVNC-NG#remote-control-via-the-intent-interface
