### ISSUE TITLE
touch input stops working after a while

### ISSUE THREAD

**Issue by phytoncidez** [bk138/droidVNC-NG#88]
**Describe the bug**

sometimes after hours, sometimes after days, all inputs including touch and key stops working.
the screen cast still works but all inputs don't get through.
if connection is stopped and reconnected it starts working again, but eventually touch input will fail.

**To Reproduce**

screen cast works but input will stop working

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - OS and version: galaxy s5, lineage 18.1
 - VNC viewer and version: realvnc, 6.0.1

**Additional context**

i think allowing root privilege will solve the problem.
i know this because older version of droid vnc (from several years ago) works fine.
the very older version allowed root privilege, which was very good and stable.

another huge advantage is as follows:
if root privilege is allowed, connection will become very stable.
also, when disconnection / reboot occurs, connection will be established automatically (without having to accept prompt).
this feature is a must, if multiple devices are running.
in this regard, newer droid vnc actually got worse than older dinosaur version.

i understand this "vnc without rooting" as your main marketing feature, similar to the marketing of now dead VM lite's vnc server.
but pros don't care about that, as they rely on solid and stable performance of rooting.

apart from this problem, i really like the droid vnc app. 
especially the home button feature, which wasn't supported in the ancient version.
but due to the input failing problem, i'd say this version is even worse than previous.
please consider allowing root connection feature for auto connection / more stable performance

**Comment by bk138** [comment]
Thanks for reporting! Which version are you using?

**Comment by phytoncidez** [comment]
> Thanks for reporting! Which version are you using? Please note this was already reported and fixed as #38

the latest version from app store.

**Comment by phytoncidez** [comment]
i'd like to know if you could develop custom app, that allows
1. root privillege
2. different app name with different icon (for stealth mode)
3. cost

my email: yasufikbar@gmail.com
please let me know

i really appreciate the work you are doing.
it's a real dedication

**Comment by bk138** [comment]
> > Thanks for reporting! Which version are you using? Please note this was already reported and fixed as #38
> 
> the latest version from play store.

Please try to get `adb logcat` logs of the situation. Otherwise it's stabbing at the dark unfortunately.

**Comment by bk138** [comment]
Tentatively closing as there was no more info from the OP. Please post here in case there's more info, we can re-open then.

**Comment by master255** [comment]
@bk138 Had this problem on 2.7.0 installed from a file.
Now I am testing 2.7.2 from the market. I'll send you Logcat if there is something there.
