### ISSUE TITLE
Please support Android 6.0

### ISSUE THREAD

**Issue by Squaregentleman** [bk138/droidVNC-NG#9]
Please support Android 6.0

**Comment by bk138** [comment]
The requirement for Android 7 was introduced by 9d05565d8892849f4b45321bf1110e91a7a3ce0b, this had to do with [a11y features introduced in Android 7](https://developer.android.com/about/versions/nougat/android-7.0#accessibility_enhancements). Adding support for Android 6 would lead to a less functional version of droidVNC-NG and also requires a significant amount of work which, TBH, I don't want to do in my free time. Please contact me via mail if you or your company need this for a business case.

**Comment by Squaregentleman** [comment]
I have a device that is Android 6.0. It doesn't have a display. I want to use VNC for it.

**Comment by Squaregentleman** [comment]
Is there any version that supports Android 6.0, as long as it can be used.

**Comment by bk138** [comment]
You can try to revert the commit mentioned above, that could work.

**Comment by Squaregentleman** [comment]
> You can try to revert the commit mentioned above, that could work.

I'll try

**Comment by Squaregentleman** [comment]
AdbProcess::out:Performing Push Install
/Users/fkj/Desktop/droidVNC-NG/app/build/outputs/apk/release/app-release-unsigned.apk: 1 file pushed. 6.8 MB/s (4707163 bytes in 0.661s)
	pkg: /data/local/tmp/app-release-unsigned.apk

AdbProcess::out:Failure [INSTALL_FAILED_OLDER_SDK]

AdbProcess::out:rm: /data/local/tmp/app-release-unsigned.apk: Permission denied

**Comment by Squaregentleman** [comment]
could not be installed

**Comment by wyl-gif** [comment]
I have implemented screen sharing on android6.0, but I can’t operate the screen, because of dispatchGesture, I need commercial support, and achieve the same effect on 6.0 and above 7.0

**Comment by bk138** [comment]
> I have implemented screen sharing on android6.0, but I can’t operate the screen, because of dispatchGesture, I need commercial support, and achieve the same effect on 6.0 and above 7.0

You can contact me via email for commercial support.

**Comment by EvgeniySpinov** [comment]
Thank you for the great software. Works like charm, but my phone is Android 6. 

Should you be interested in Android 6 buildable version - please check out my fork and spare branch for it. https://github.com/EvgeniySpinov/droidVNC-NG/tree/android-6

I've cleaned up mentioned commit in this thread as well as related ones, which made droidVNC-NG screen readonly. It's very limited use case, but suit my needs. Decided to share.

Version I've cleaned was 1.0.2.

**Comment by Squaregentleman** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by OmlineEditor** [comment]
make support for old systems Android 6.

**Comment by bk138** [comment]
@OmlineEditor please see @EvgeniySpinov 's branch

**Comment by OmlineEditor** [comment]
> please see @EvgeniySpinov 's branch

I saw it, I want you to add this feature to yourself

**Comment by bk138** [comment]
> > please see @EvgeniySpinov 's branch
> 
> I saw it, I want you to add this feature to yourself

Alright. In this case, https://github.com/bk138/droidVNC-NG/issues/9#issuecomment-784013564 still holds true.

**Comment by OmlineEditor** [comment]
> Alright. In this case, [#9 (comment)](https://github.com/bk138/droidVNC-NG/issues/9#issuecomment-784013564) still holds true.

you can take part of the code from the [fork](https://github.com/EvgeniySpinov/droidVNC-NG/tree/android-6) that there is less work for you?

**Comment by bk138** [comment]
Closing as wontfix. This is getting more and more outdated and there is https://github.com/bk138/droidVNC-NG/issues/9#issuecomment-1151672487 which offers a working build for Android 6.

**Comment by pergolafabio** [comment]
is there anyone who can share an apk that works with android 5 ?

thnx in advance!!
