### ISSUE TITLE
REDMI 9A not connecting

### ISSUE THREAD

**Issue by SANTHOSHPILLAI6** [bk138/droidVNC-NG#91]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**

**To Reproduce**

**Expected Behavior**

**Logs/Backtraces**

**Your environment (please complete the following information):**
 - droidVNC-NG version:
 - Android version:
 - Client-side OS and version:
 - VNC client and version:

**Additional context**

**Comment by SANTHOSHPILLAI6** [comment]
REDMI 9A not connecting, showing error that the other party did not respond properly after a period of time or established connection failed because connected host has failed to respond.....Checked firewall in android and also the downloaded services accessibility permission

**Comment by bk138** [comment]
Hi, thanks for your report! Can you please describe what you're trying to do and which results you expect? (Normal VNC vs reverseVNC, LAN vs WAN).

Also, please provide info about your environment:
* droidVNC-NG version:
* Android version:
* Client-side OS and version:
* VNC client and version:

**Comment by bk138** [comment]
Tentatively closing, feel free to post additional info here so we can possibly re-open.
