### ISSUE TITLE
Start localhost:5900 connection automatically from Termux (script)

### ISSUE THREAD

**Issue by temporarium** [bk138/droidVNC-NG#93]
I can connect to my Android device via a reverse ssh tunnel to my server, and I can then start droidVNC-NG and connect to an "LISTENING VIEWER" - 127.0.0.1:5900, which allows me to connect to it and control my phone over that ssh connection.

What I would like to request (or know if there is already a way to do it) is to be able to launch droidVNC-NG (vnc server) - started and connected to 127.0.0.1:5900 - from a Termux script or (alternatively) from MacroDroid - preferably in the background.

Edit: I have managed to get it started and terminated via UI actions in MacroDroid, but I would really prefer a command-line start.

**Comment by bk138** [comment]
This is tracked in #83 and tackled by #84 - you'd be sending Intents to droidVNC-NG.

**Comment by temporarium** [comment]
OK. Sorry for the duplicate and thank you for considering it. Will await the merges :-)

**Comment by bk138** [comment]
See https://github.com/bk138/droidVNC-NG#remote-control-via-the-intent-interface
