### ISSUE TITLE
Crash: rect too big

### ISSUE THREAD

**Issue by InfinityLoop1309** [bk138/droidVNC-NG#94]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/droidVNC-NG

**Describe the bug**
After connected to my Android phone using vncviewer, the connection will crash every 5-15 minutes.

**To Reproduce**

**Expected Behavior**

No crash.

**Logs/Backtraces**

Wed Jul 27 07:55:39 2022
 CMsgReader:  Rect too big: 65535x65528 at 768,0 exceeds 448x960
 CConn:       Rect too big

**Your environment (please complete the following information):**
 - droidVNC-NG version: fdroid latest
 - Android version: 11
 - Client-side OS and version: fedora35 kernel 5.17.7
 - VNC client and version: vncviewer v1.12.0

**Additional context**

I have no background in VNC, but if you can point me the problem, I may fix it myself.

**Comment by InfinityLoop1309** [comment]
It turns out I have wrong configuration of my VNC viewer. Uncheck the "auto select" options fixed it, and it works well now.

**Comment by bk138** [comment]
@InfinityLoop1309 I've had these too with the TigerVNC viewer, it's got something to do with the viewer changing encodings and/or pixelformats while the connection is active. https://topic.alibabacloud.com/a/vnc-appeared-rect-too-big-problem-solved_8_8_10247673.html has some info on this.
