### ISSUE TITLE
Config deployment?

### ISSUE THREAD

**Issue by Laser5000** [bk138/droidVNC-NG#96]
Hi, is it possible to deploy the configuration? Where is it saved?

best regards

**Comment by bk138** [comment]
It's saved in [SharedPreferences](https://stackoverflow.com/questions/6146106/where-are-shared-preferences-stored), so one should be able to read the file and deploy it to other devices. I haven't tested this tough. Do you need commercial support?

**Comment by bk138** [comment]
I just see this is actually a dupe of #54 - let's tackle this there together.
