### ISSUE TITLE
App frequently asks for screen recording permissions

### ISSUE THREAD

**Issue by shalak** [bk138/droidVNC-NG#99]
**Describe the bug**
I use droidVNC on a phone that acts as a smart-home display that shows Home Assistant in kiosk mode. I find myself unable to perform any screen input actions via VNC, although I'm able to connect and see the screen as well as press the "Home button" via VNC client. Once I unlock the screen manually, the android request to grant screen-recording permissions is shown, once I allow it everything works correctly.

**To Reproduce**
1. Start droidVNC on a device that's persistently connected to USB
2. Wait big amount of time

**Expected Behavior**
The screen-recording permission is persistent 

**Actual Behavior**
The screen-recording permission is revoked and must be "re-granted"

**Your environment (please complete the following information):**
 - droidVNC-NG version: 1.3.3
 - Android version: 12
 - Client-side OS and version: MacOS Monterey 12.5
 - VNC client and version: VNC Viewer 6.21.1109

**Additional context**
I'm not sure how much time do I have to wait for the permissions to be revoked, but it might be related to the fact that the screen becomes blocked. It usually happens after I update my Home Assistant server and as a consequence the HA client app running on the phone shuts down, thus eventually blocking the screen and revoking permissions for droidVNC

**Comment by bk138** [comment]
I don't really know what's going on to be honest. What _might_ happen is that Android kills the Service and restart it, you might find something in the logs.

What you might try is:
* Try to see if the same happens with ScreenRecorder as described in https://github.com/bk138/droidVNC-NG#notes
* Grant the permission permanently via adb as described in https://github.com/bk138/droidVNC-NG#notes

**Comment by phytoncidez** [comment]
> I don't really know what's going on to be honest. What _might_ happen is that Android kills the Service and restart it, you might find something in the logs.
> 
> What you might try is:
> 
> * Try to see if the same happens with ScreenRecorder as described in https://github.com/bk138/droidVNC-NG#notes
> * Grant the permission permanently via adb as described in https://github.com/bk138/droidVNC-NG#notes


i have extensive experience with the old droid vnc
the old one doesn't have this problem, because it allows root access.
it works for months without any problem.
please add root privilege as option

**Comment by phytoncidez** [comment]
> I don't really know what's going on to be honest. What _might_ happen is that Android kills the Service and restart it, you might find something in the logs.
> 
> What you might try is:
> 
> * Try to see if the same happens with ScreenRecorder as described in https://github.com/bk138/droidVNC-NG#notes
> * Grant the permission permanently via adb as described in https://github.com/bk138/droidVNC-NG#notes

is the permmision grant via adb permanent? even if the device restarts?
if so, this is the solution

**Comment by bk138** [comment]
> i have extensive experience with the old droid vnc the old one doesn't have this problem, because it allows root access. it works for months without any problem. please add root privilege as option

That's tracked in #31, please have a look there and subscribe, if you like.

**Comment by bk138** [comment]
> is the permmision grant via adb permanent? even if the device restarts? if so, this is the solution

AFAIK yes. You should try it out. Please report here if it works for you.

**Comment by bk138** [comment]
Tentatively closing, fell free to post here if there are news.
